model_name: TACE-OAM-L
model_key: tace-oam-l
model_version: '0.2.0'
dates:
  benchmark_added: '2026-04-09'
  paper_published: '2026-04-09'
lifecycle: active
authors:
- name: Zemin Xu
  affiliation: ShanghaiTech University, Nanjing University
  email: xv_chana@foxmail.com
  github: https://github.com/xvzemin
  corresponding: false
- name: Wenbo Xie
  affiliation: ShanghaiTech University
  email: xiewb1@shanghaitech.edu.cn
  orcid: https://orcid.org/0000-0001-5321-2494
  corresponding: true
- name: P. Hu
  affiliation: ShanghaiTech University
  email: hupj@shanghaitech.edu.cn
  orcid: https://orcid.org/0000-0002-6318-1051
  corresponding: true
trained_by:
- name: Zemin Xu
  affiliation: ShanghaiTech University, Nanjing University
  email: xv_chana@foxmail.com
  github: https://github.com/xvzemin
  corresponding: false

repo: https://github.com/xvzemin/tace
doi: https://doi.org/10.57967/hf/7458
paper: https://arxiv.org/abs/2509.14961
docs: https://github.com/xvzemin/tace
pr_url: https://github.com/janosh/matbench-discovery/pull/321
checkpoint_url: https://huggingface.co/xvzemin/tace-foundations/resolve/main/TACE-OAM-L.pt
license:
  code: MIT
  code_url: https://github.com/xvzemin/tace/blob/main/LICENSE.md
  checkpoint: CC-BY-4.0
  # URL that points to the license file for the model checkpoint, not the checkpoint file itself.
  checkpoint_url: https://creativecommons.org/licenses/by/4.0/legalcode

environment:
  dependencies:
  - tace @ git+https://github.com/xvzemin/tace@c669bee71c2f157dce80d80e8a8f0a08ddfc124c
  - torch==2.9.1
  - torch-geometric==2.7.0
  - pytorch-lightning==2.5.5
  python_version: '3.12'
openness: OSOD
architecture_types: [gnn]
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
training_sets: [MPtrj, OMat24, sAlex]
model_params: 82899905
training_cost:
  entries:
  - hardware: NVIDIA H20
    count: 8
    hours_per_device: 105.0
hyperparams:
  evaluation:
    max_force: 0.02
    max_steps: 500
    ase_optimizer: FIRE
    cell_filter: FrechetCellFilter
    kappa:
      protocol: phonondb-v1
      displacement_distance: 0.03
      save_forces: true
  architecture:
    graph_construction_radius: 6.0
    n_layers: 5
  training:
    epochs: 3
    initial_learning_rate: 0.008
    optimizer: AdamW
    batch_size: 1024
  upstream_config:
    loss_weights:
      energy: 1
      force: 1
      stress: 0.1
    huber_delta: [0.015, 0.040, 0.1]
    num_channel: 64
    lmax: 5
    l1l2: l1 <= l2
    correlation: 2
notes:
  description: |
    Support both Spherical tensor and irreducible Cartesian tensor.
  steps: |
    Training performed by: (1) pre-training on 3 epoch OMat24 (lr-8e-3, loss-1:1:0.1); (2) fine-tuning on on 3 epoch MPtrj+sAlex (lr-1e-4, loss-1:1:0.1).

metrics:
  diatomics:
    pred_file:
      name: models/tace/tace-oam-l/2026-06-29-diatomics.json.gz
      url: https://figshare.com/files/66104666
      size: 223996
      md5: f1f24220e1e26ea1b58ea30b0e145dca
    hardware: NVIDIA H200
    run_time_sec: 1300.3
    pbe_wall_dist_mae: 0.1119
    pbe_energy_mae: 0.9634
    pbe_bond_length_error: 0.2021
    pbe_well_depth_error: 0.6152
    pbe_vib_freq_error: 42.78
    tortuosity: 1.007
    energy_diff_flips: 1.632
    energy_jump: 0.1254
    force_flips: 1.598
    force_total_variation: 179.1
    force_jump: 4.72
    pbe_force_mae: 0.9552
  discovery:
    pred_file:                                                    # tace-filtered_preds.csv.gz tace-preds.csv.gz
      name: models/tace/tace-oam-l/2026-04-09-discovery.csv.gz
      url: https://figshare.com/files/63590511
      size: 1648063
      md5: deecc3cbb9f2695f5e5ce1763e216ba6
    pred_col: e_form_per_atom_tace
    full_test_set:
      F1: 0.892  # fraction
      DAF: 5.127 # dimensionless
      Precision: 0.88 # fraction
      Recall: 0.904 # fraction
      Accuracy: 0.962 # fraction
      TPR: 0.904 # fraction
      FPR: 0.026 # fraction
      TNR: 0.974 # fraction
      FNR: 0.096 # fraction
      TP: 39872 # count
      FP: 5454 # count
      TN: 207417 # count
      FN: 4220 # count
      MAE: 0.02 # eV/atom
      RMSE: 0.067 # eV/atom
      R2: 0.862 # dimensionless
      missing_preds: 3 # count
    most_stable_10k:
      F1: 0.985  # fraction
      DAF: 6.347 # dimensionless
      Precision: 0.97 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.97 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9702 # count
      FP: 298 # count
      TN: 0 # count
      FN: 0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.079 # eV/atom
      R2: 0.867 # dimensionless
      missing_preds: 0 # count
    unique_prototypes:
      F1: 0.91  # fraction
      DAF: 5.898 # dimensionless
      Precision: 0.902 # fraction
      Recall: 0.919 # fraction
      Accuracy: 0.972 # fraction
      TPR: 0.919 # fraction
      FPR: 0.018 # fraction
      TNR: 0.982 # fraction
      FNR: 0.081 # fraction
      TP: 30661 # count
      FP: 3344 # count
      TN: 178770 # count
      FN: 2713 # count
      MAE: 0.02 # eV/atom
      RMSE: 0.067 # eV/atom
      R2: 0.868 # dimensionless
      missing_preds: 1 # count
  geo_opt:
    pred_file:
      name: models/tace/tace-oam-l/2026-04-09-geo-opt.jsonl.gz
      url: https://figshare.com/files/63594915
      size: 106885046
      md5: d0c21952707f9cdf309056591ceeff35
    symprec=1e-2:
      rmsd: 0.0606
      n_sym_ops_mae: 1.7042
      symmetry_decrease: 0.0479
      symmetry_match: 0.8188
      symmetry_increase: 0.126
      n_structures: 256963
      analysis_file:
        name: models/tace/tace-oam-l/2026-04-09-geo-opt-symprec=1e-2-moyo=0.7.9.csv.gz
        url: https://figshare.com/files/63594918
        size: 8167900
        md5: 68843ec42faf0ebe1c317ccfa6e7f8df
    symprec=1e-5:
      rmsd: 0.0606
      n_sym_ops_mae: 2.1326
      symmetry_decrease: 0.0603
      symmetry_match: 0.6922
      symmetry_increase: 0.2415
      n_structures: 256963
      analysis_file:
        name: models/tace/tace-oam-l/2026-04-09-geo-opt-symprec=1e-5-moyo=0.7.9.csv.gz
        url: https://figshare.com/files/63594921
        size: 8113780
        md5: 41799783e40720c96e191d8921bbc432
  md:
    pred_file:
      name: models/tace/tace-oam-l/2026-06-28-md-metrics.csv.gz
      url: https://figshare.com/files/66048938
      size: 1583
      md5: f08d7b7ed68e032e925b6982d3e4b683
    hardware: NVIDIA H200
    run_time_sec: 199194.77
    energy_rmse: 0.5479
    force_rmse: 60.1476
    rdf_error: 3.4228
    adf_error: 1.3286
    vdos_error: 22.4849
    pressure_mae: 0.7461
    pressure_wasserstein: 0.7541
    pressure_error: 42.6072
    n_systems: 17
  phonons:
    kappa_103:
      pred_file:
        name: models/tace/tace-oam-l/2026-04-09-phonons-kappa-103.json.gz
        url: https://figshare.com/files/63590373
        size: 8215708
        md5: c9b3fe92fd4c3d03627fa9f6ea9ab2b7
      κ_SRME: 0.126
      κ_SRE: 0.0502
