model_name: TECE-OAM-RRA-1.0
model_key: tece-oam-rra-1.0
model_version: v2026.07.05
dates:
  benchmark_added: '2026-07-05'
  paper_published: '2026-07-05'
lifecycle: active
authors:
  - name: Zemin Xu
    affiliation: ShanghaiTech University, Nanjing University
    email: xv_chana@foxmail.com
    github: https://github.com/xvzemin
    corresponding: false
  - name: Wenbo Xie
    affiliation: ShanghaiTech University
    email: xiewb1@shanghaitech.edu.cn
    orcid: https://orcid.org/0000-0001-5321-2494
    corresponding: true
  - name: P. Hu
    affiliation: ShanghaiTech University
    email: hupj@shanghaitech.edu.cn
    orcid: https://orcid.org/0000-0002-6318-1051
    corresponding: true
trained_by:
  - name: Zemin Xu
    affiliation: ShanghaiTech University, Nanjing University
    email: xv_chana@foxmail.com
    github: https://github.com/xvzemin
    corresponding: false

repo: https://github.com/xvzemin/tace
doi: https://doi.org/10.57967/hf/7458
paper: https://arxiv.org/abs/2509.14961
docs: https://github.com/xvzemin/tace
pr_url: https://github.com/janosh/matbench-discovery/pull/365
checkpoint_url: https://huggingface.co/xvzemin/tace-foundations/resolve/main/TECE-OAM-RRA-1.0.pt
license:
  code: MIT
  code_url: https://github.com/xvzemin/tace/blob/main/LICENSE.md
  checkpoint: CC-BY-4.0
  # URL that points to the license file for the model checkpoint, not the checkpoint file itself.
  checkpoint_url: https://creativecommons.org/licenses/by/4.0/legalcode

environment:
  dependencies:
    - tace @ git+https://github.com/xvzemin/tace@88d8dcd5724e94751783b0a3405cb49573af1583
    - torch==2.9.1
    - torch-geometric==2.7.0
    - pytorch-lightning==2.5.5
  python_version: '3.12'
openness: OSOD
architecture_types: [gnn]
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
training_sets: [MPtrj, OMat24, sAlex]
model_params: 221853358
training_cost:
  entries:
    - hardware: NVIDIA H20
      count: 32
      hours_per_device: 240.0
hyperparams:
  evaluation:
    max_force: 0.02
    max_steps: 500
    ase_optimizer: FIRE
    cell_filter: FrechetCellFilter
    kappa:
      protocol: phonondb-v1
      displacement_distance: 0.03
      save_forces: true
  architecture:
    graph_construction_radius: 6.0
    n_layers: 8
  training:
    epochs: 3
    batch_size: 512
  upstream_config:
    loss_weights:
      energy: 1
      force: 1
      stress: 1
    num_interaction_channel: 64
    num_product_channel: 256
    mmax: 4
    Lmax: 4
    lmax: 4
    l1l2: <=
    correlation: 2
notes:
  description: |
    This model is based on Atomic Cluster Expansion, Edge Cluster Expansion
    and Radial Rotary Attention.

metrics:
  diatomics:
    pred_file:
      name: models/tace/tece-oam-rra-1.0/2026-07-05-diatomics.json.gz
      url: https://figshare.com/files/66313844
    hardware: NVIDIA GeForce RTX 4090
    run_time_sec: 4505.61
    pbe_wall_dist_mae: 0.3074
    pbe_energy_mae: 3.918
    pbe_bond_length_error: 0.6948
    pbe_well_depth_error: 0.7725
    pbe_vib_freq_error: 82.38
    tortuosity: 1.335
    energy_diff_flips: 3.805
    energy_jump: 2.718
    force_flips: 3.586
    force_total_variation: 299.6
    force_jump: 70.17
    pbe_force_mae: 2.315
  discovery:
    pred_file:
      name: models/tace/tece-oam-rra-1.0/2026-07-05-discovery.csv.gz
      url: https://figshare.com/files/66313757
    full_test_set:
      F1: 0.91  # fraction
      DAF: 5.3 # dimensionless
      Precision: 0.909 # fraction
      Recall: 0.911 # fraction
      Accuracy: 0.969 # fraction
      TPR: 0.911 # fraction
      FPR: 0.019 # fraction
      TNR: 0.981 # fraction
      FNR: 0.089 # fraction
      TP: 40171 # count
      FP: 4000 # count
      TN: 208871 # count
      FN: 3921 # count
      MAE: 0.017 # eV/atom
      RMSE: 0.066 # eV/atom
      R2: 0.865 # dimensionless
      missing_preds: 2 # count
    most_stable_10k:
      F1: 0.987  # fraction
      DAF: 6.367 # dimensionless
      Precision: 0.973 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.973 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9734 # count
      FP: 266 # count
      TN: 0 # count
      FN: 0 # count
      MAE: 0.015 # eV/atom
      RMSE: 0.065 # eV/atom
      R2: 0.905 # dimensionless
      missing_preds: 0 # count
    unique_prototypes:
      F1: 0.929  # fraction
      DAF: 6.073 # dimensionless
      Precision: 0.928 # fraction
      Recall: 0.93 # fraction
      Accuracy: 0.978 # fraction
      TPR: 0.93 # fraction
      FPR: 0.013 # fraction
      TNR: 0.987 # fraction
      FNR: 0.07 # fraction
      TP: 31027 # count
      FP: 2392 # count
      TN: 179722 # count
      FN: 2347 # count
      MAE: 0.018 # eV/atom
      RMSE: 0.066 # eV/atom
      R2: 0.871 # dimensionless
      missing_preds: 0 # count
  geo_opt:
    pred_file:
      name: models/tace/tece-oam-rra-1.0/2026-07-05-geo-opt.jsonl.gz
      url: https://figshare.com/files/66313751
    symprec=1e-2:
      rmsd: 0.0575
      n_sym_ops_mae: 1.6991
      symmetry_decrease: 0.0498
      symmetry_match: 0.8183
      symmetry_increase: 0.1245
      n_structures: 256963
      analysis_file:
        name: models/tace/tece-oam-rra-1.0/2026-07-05-geo-opt-symprec=1e-2-moyo=0.14.0.csv.gz
        url: https://figshare.com/files/66313874
    symprec=1e-5:
      rmsd: 0.0575
      n_sym_ops_mae: 2.7951
      symmetry_decrease: 0.1846
      symmetry_match: 0.5907
      symmetry_increase: 0.2102
      n_structures: 256963
      analysis_file:
        name: models/tace/tece-oam-rra-1.0/2026-07-05-geo-opt-symprec=1e-5-moyo=0.14.0.csv.gz
        url: https://figshare.com/files/66313868
  md:
    pred_file:
      name: models/tace/tece-oam-rra-1.0/2026-07-05-md-metrics.csv.gz
      url: https://figshare.com/files/66323729
    hardware: NVIDIA H200
    run_time_sec: 401724.73
    energy_rmse: 0.4353
    force_rmse: 42.3737
    rdf_error: 3.1337
    adf_error: 1.3021
    vdos_error: 21.6274
    pressure_mae: 0.81
    pressure_wasserstein: 0.8162
    pressure_error: 44.5257
    n_systems: 17
  phonons:
    kappa_103:
      pred_file:
        name: models/tace/tece-oam-rra-1.0/2026-07-05-phonons-kappa-103.json.gz
        url: https://figshare.com/files/66313763
      κ_SRME: 0.0927
      κ_SRE: 0.0447
