changelog:
  exclude:
    authors: [github-actions, pre-commit-ci]
  categories:
    - title: 💥 Breaking Changes
      labels: [breaking]
    - title: 🆕 New Model
      labels: [new model]
    - title: 🎉 New Features
      labels: [feature]
    - title: 🛠 Enhancements
      labels: [enhancement, DX, UX]
    - title: 🐛 Bug Fixes
      labels: [fix]
    - title: 📖 Documentation
      labels: [docs]
    - title: 🌐 Site Upgrades
      labels: [site]
    - title: 🧹 House-Keeping
      labels: [housekeeping]
    - title: 🚀 Performance
      labels: [performance]
    - title: 🚧 CI
      labels: [ci]
    - title: 💡 Refactoring
      labels: [refactor]
    - title: 🧪 Tests
      labels: [tests]
    - title: 🔒 Security Fixes
      labels: [security]
    - title: 🏥 Package Health
      labels: [pkg]
    - title: 📦 Dependencies
      labels: [dependencies, outdated]
    - title: 🏷️ Type Hints
      labels: [types]
    - title: 🤷‍♂️ Other Changes
      labels: ['*']
