model:
  chemical_species: univ
  cutoff: 6.0
  channel: 128
  irreps_manual:
    - 128x0e
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e
  lmax: 3
  is_parity: true
  num_convolution_layer: 12
  radial_basis:
    radial_basis_name: bessel
    bessel_basis_num: 8
  cutoff_function:
    cutoff_function_name: XPLOR
    cutoff_on: 5.5
  act_radial: silu
  weight_nn_hidden_neurons:
    - 64
    - 64
  act_scalar:
    e: silu
    o: tanh
  act_gate:
    e: silu
    o: tanh
  train_denominator: false
  train_shift_scale: false
  train_shift: true
  train_scale: false
  use_bias_in_linear: false
  use_modal_node_embedding: false
  use_modal_self_inter_intro: true
  use_modal_self_inter_outro: true
  use_modal_output_block: true
  readout_as_fcn: false
  self_connection_type: nequip
  interaction_type: nequip
train:
  random_seed: 77777
  epoch: 1
  loss:
    energy:
      loss_weight: 1.0
      loss_type: mae
    force:
      loss_weight: 1.0
      loss_type: l2mae
    stress:
      loss_weight: 0.0005
      loss_type: l2mae
  loss_param: {}
  optimizer: adam
  optim_param:
    lr: 0.0001
  scheduler: onecyclelr
  scheduler_param:
    max_lr: 0.0001
    epochs: 1
    pct_start: 0.05
    anneal_strategy: cos
    div_factor: 25.0
    final_div_factor: 10000.0
    total_steps: 1755026
  per_epoch: 0.0025
  grad_clip: 1000
  is_train_stress: true
  train_shuffle: true
  error_record:
    - - Energy
      - MAE
    - - Force
      - L2MAE
    - - Stress
      - L2MAE
    - - Energy
      - Loss
    - - Force
      - Loss
    - - Stress
      - Loss
    - - L2_modal
      - Loss
    - - TotalLoss
      - None
  best_metric: TotalLoss
  use_modality: true
  regularization_param:
    modal:
      regularization_weight: 1e-6
data:
  dtype: single
  data_format: ase
  data_format_args: {}
  batch_size: 256
  compute_statistics: true
  dataset_type: custom
  use_modal_wise_shift: true
  use_modal_wise_scale: false
  load_trainset_path:
    - data_modality: omat24
      file_list:
        - file: '**path_to_omat24**'
    - data_modality: mpa
      file_list:
        - file: '**path_to_mpa**'
    - data_modality: omol25_low
      file_list:
        - file: '**path_to_omol25_low**'
    - data_modality: omol25_high
      file_list:
        - file: '**path_to_omol25_high**'
    - data_modality: matpes_pbe
      file_list:
        - file: '**path_to_matpes_pbe**'
    - data_modality: matpes_r2scan
      file_list:
        - file: '**path_to_matpes_r2scan**'
    - data_modality: mp_r2scan
      file_list:
        - file: '**path_to_mp_r2scan**'
    - data_modality: oc20
      file_list:
        - file: '**path_to_oc20**'
    - data_modality: oc22
      file_list:
        - file: '**path_to_oc22**'
    - data_modality: spice
      file_list:
        - file: '**path_to_spice**'
    - data_modality: qcml
      file_list:
        - file: '**path_to_qcml**'
    - data_modality: odac23
      file_list:
        - file: '**path_to_odac23**'
    - data_modality: pet_mad
      file_list:
        - file: '**path_to_pet_mad**'
  load_validset_path: '**path_to_validset**'
  shift: '**failed to infer shift, should be set**'
  scale: '**failed to infer scale, should be set**'
