model:
  chemical_species: univ
  cutoff: 6.0
  channel: 128
  irreps_manual:
    - 128x0e
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+64x1e+32x2o+32x2e+32x3o+32x3e
    - 128x0o+128x0e+64x1o+64x1e+32x2o+32x2e+32x3o+32x3e
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e
  lmax: 3
  is_parity: true
  num_convolution_layer: 5
  radial_basis:
    radial_basis_name: bessel
    bessel_basis_num: 8
  cutoff_function:
    cutoff_function_name: XPLOR
    cutoff_on: 5.5
  act_radial: silu
  weight_nn_hidden_neurons:
    - 64
    - 64
  act_scalar:
    e: silu
    o: tanh
  act_gate:
    e: silu
    o: tanh
  train_denominator: false
  train_shift_scale: false
  train_shift: true
  train_scale: false
  use_bias_in_linear: false
  use_modal_node_embedding: false
  use_modal_self_inter_intro: true
  use_modal_self_inter_outro: true
  use_modal_output_block: true
  readout_as_fcn: false
  self_connection_type: nequip
  interaction_type: nequip
train:
  random_seed: 777
  epoch: 2
  loss:
    energy:
      loss_weight: 1.0
      loss_type: mae
    force:
      loss_weight: 0.1
      loss_type: l2mae
    stress:
      loss_weight: 0.0001
      loss_type: l2mae
  loss_param: {}
  optimizer: adamw
  optim_param:
    lr: 0.0002
    weight_decay: 0.001
  scheduler: onecyclelr
  scheduler_param:
    max_lr: 0.0002
    epochs: 2
    pct_start: 0.005
    anneal_strategy: cos
    div_factor: 25.0
    final_div_factor: 10000.0
    total_steps: 1007534
  model_averaging: EMA
  model_averaging_param:
    ema_decay_factor: 0.999
  grad_clip: 100
  energy_loss_weight: 1.0
  force_loss_weight: 0.1
  stress_loss_weight: 1.0e-06
  regularization_weight: 0.0
  per_epoch: 0.005
  train_by_batch: true
  csv_log: log.csv
  num_workers: 0
  is_train_stress: true
  train_shuffle: true
  error_record:
    - - Energy
      - MAE
    - - Force
      - MAE
    - - Stress
      - MAE
    - - Energy
      - Loss
    - - Force
      - Loss
    - - Stress
      - Loss
    - - L2_modal
      - Loss
    - - Modal_cos
      - None
    - - TotalLoss
      - None
  best_metric: TotalLoss
  use_weight: false
  use_modality: true
  compile: false
  use_regularization: false
data:
  dtype: single
  data_format: ase
  data_format_args: {}
  batch_size: 512 # global batch size
  compute_statistics: true
  dataset_type: custom
  use_modal_wise_shift: true
  use_modal_wise_scale: false
  loader_kwargs:
    num_workers: 2
    pin_memory: true
  load_trainset_path:
    - data_modality: omat24
      file_list:
        - file: "**path_to_omat24**"
    - data_modality: mpa
      file_list:
        - file: "**path_to_mpa**"
  load_validset_path: "**path_to_validset**"
  shift: "**failed to infer shift, should be set**"
  scale: "**failed to infer scale, should be set**"
