model_name: MatRIS-10M-OAM
model_key: matris-10m-oam
model_version: v1
date_added: '2025-10-29'
date_published: '2025-10-29'
authors:
  - name: Yuanchang Zhou
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: zhouyuanchang23s@ict.ac.cn
    orcid: https://orcid.org/0009-0004-6801-7033
  - name: Siyu Hu
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: husiyu@ict.ac.cn
    orcid: https://orcid.org/0009-0008-6085-4645
  - name: Guangming Tan
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: tgm@ict.ac.cn
    orcid: https://orcid.org/0000-0002-6361-5948
  - name: Weile Jia
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: jiaweile@ict.ac.cn
    orcid: https://orcid.org/0000-0001-8539-8326
    corresponding: true
trained_by:
  - name: Yuanchang Zhou
    affiliation: Institute of Computing Technology, Chinese Academy of Sciences
    email: zhouyuanchang23s@ict.ac.cn
    orcid: https://orcid.org/0009-0004-6801-7033

repo: https://github.com/HPC-AI-Team/MatRIS
url: https://github.com/HPC-AI-Team/MatRIS
doi: https://github.com/HPC-AI-Team/MatRIS # no paper yet, using repo URL
paper: https://github.com/HPC-AI-Team/MatRIS # no paper yet, using repo URL
pr_url: https://github.com/janosh/matbench-discovery/pull/293
checkpoint_url: https://figshare.com/files/59142728

license:
  code: BSD-3-Clause
  code_url: https://github.com/HPC-AI-Team/MatRIS/blob/main/LICENSE
  checkpoint: BSD-3-Clause
  checkpoint_url: https://github.com/HPC-AI-Team/MatRIS/blob/main/LICENSE

openness: OSOD
train_task: S2EFSM
test_task: IS2RE-SR
targets: EFS_GM
model_type: UIP
model_params: 10_443_505
trained_for_benchmark: false
n_estimators: 1

hyperparams:
  max_force: 0.02
  max_steps: 500
  ase_optimizer: FIRE
  optimizer: AdamW(wd=1e-3)
  cell_filter: FrechetCellFilter
  loss: MAE/L2MAE
  loss_weights:
    energy: 5.0
    force: 5.0
    stress: 0.1
    magmom: 0.1
  batch_size: 512
  initial_learning_rate: 0.0003
  learning_rate_schedule: CosineAnnealingLR(T_max=50)
  n_layers: 10
  graph_construction_radius: 6.0 # Å
  three_body_cutoff: 4.5 # Å
  max_neighbors: .inf

requirements:
  torch: 2.6.0
  ase: 3.26.0
  pymatgen: 2025.10.07
  numpy: 2.3.4

training_set: [OMat24, sAlex, MPtrj]

training_cost:
  Nvidia H100 GPUs: { amount: 64, hours: 80 }

notes:
  Description: |
    MatRIS is a foundation model for materials representation and interaction simulation.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 0.2183
      κ_SRE: 0.1181
      pred_file: models/matris/matris-10m-oam/2025-10-29-kappa-103-fire-dist=0.03-fmax1e-5-symprec1e-5.json.gz
      pred_file_url: https://figshare.com/files/59234180
  geo_opt:
    pred_file: models/matris/matris-10m-oam/2025-10-29-wbm-IS2RE.json.gz
    pred_file_url: https://figshare.com/files/59233958
    struct_col: matris_structure

    symprec=1e-2:
      rmsd: 0.0601 # unitless
      n_sym_ops_mae: 1.732 # unitless
      symmetry_decrease: 0.0547 # fraction
      symmetry_match: 0.8153 # fraction
      symmetry_increase: 0.1227 # fraction
      n_structures: 256963 # count
      analysis_file: models/matris/matris-10m-oam/2025-10-29-wbm-IS2RE-symprec=1e-2-moyo=0.4.6.csv.gz
      analysis_file_url: https://figshare.com/files/59234063
    symprec=1e-5:
      rmsd: 0.0601 # unitless
      n_sym_ops_mae: 3.0682 # unitless
      symmetry_decrease: 0.195 # fraction
      symmetry_match: 0.5955 # fraction
      symmetry_increase: 0.1996 # fraction
      n_structures: 256963 # count
      analysis_file: models/matris/matris-10m-oam/2025-10-29-wbm-IS2RE-symprec=1e-5-moyo=0.4.6.csv.gz
      analysis_file_url: https://figshare.com/files/59234102
  discovery:
    pred_file: models/matris/matris-10m-oam/2025-10-29-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/files/59233856
    pred_col: e_form_per_atom_matris

    #diatomics:
    #  pred_file: models/matris/matris-10m-oam/2025-10-29-diatomics.json.gz
    #  pred_file_url: https://figshare.com/files/59154077
    full_test_set:
      F1: 0.903 # fraction
      DAF: 5.275 # dimensionless
      Precision: 0.905 # fraction
      Recall: 0.901 # fraction
      Accuracy: 0.967 # fraction
      TPR: 0.901 # fraction
      FPR: 0.02 # fraction
      TNR: 0.98 # fraction
      FNR: 0.099 # fraction
      TP: 39723.0 # count
      FP: 4162.0 # count
      TN: 208709.0 # count
      FN: 4369.0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.066 # eV/atom
      R2: 0.864 # dimensionless
      missing_preds: 2 # count
    unique_prototypes:
      F1: 0.921 # fraction
      DAF: 6.039 # dimensionless
      Precision: 0.923 # fraction
      Recall: 0.918 # fraction
      Accuracy: 0.976 # fraction
      TPR: 0.918 # fraction
      FPR: 0.014 # fraction
      TNR: 0.986 # fraction
      FNR: 0.082 # fraction
      TP: 30652.0 # count
      FP: 2548.0 # count
      TN: 179566.0 # count
      FN: 2722.0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.066 # eV/atom
      R2: 0.871 # dimensionless
      missing_preds: 0 # count
    most_stable_10k:
      F1: 0.986 # fraction
      DAF: 6.366 # dimensionless
      Precision: 0.973 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.973 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9732.0 # count
      FP: 268.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.015 # eV/atom
      RMSE: 0.066 # eV/atom
      R2: 0.904 # dimensionless
      missing_preds: 0 # count
