model_name: eqV2
model_version: v2024.10.18
matbench_discovery_version: 1.3.1
date_added: "2024-10-18"
date_published: "2024-10-18"
authors:
  - name: Luis Barroso-Luque
    affiliation: FAIR Meta
    email: lbluque@meta.com
    orcid: https://orcid.org/0000-0002-6453-9545
    github: https://github.com/lbluque
    corresponding: true
  - name: Muhammed Shuaibi
    affiliation: FAIR Meta
  - name: Xiang Fu
    affiliation: FAIR Meta
  - name: Brandon M. Wood
    affiliation: FAIR Meta
  - name: Misko Dzamba
    affiliation: FAIR Meta
  - name: Meng Gao
    affiliation: FAIR Meta
  - name: Ammar Rizvi
    affiliation: FAIR Meta
  - name: C.~Lawrence Zitnick
    affiliation: FAIR Meta
  - name: Zachary W. Ulissi
    affiliation: FAIR Meta
    email: zulissi@meta.com
    orcid: https://orcid.org/0000-0002-9401-4918
    corresponding: true

repo: https://github.com/FAIR-Chem/fairchem
doi: https://doi.org/10.48550/arXiv.2410.12771
paper: https://arxiv.org/abs/2410.12771
url: https://huggingface.co/fairchem/OMAT24
pypi: https://pypi.org/project/fairchem-core

requirements:
  fairchem-core: 1.2.1

pred_col: e_form_per_atom_eqV2-86M-omat-mp-salex

openness: OSOD
trained_for_benchmark: true
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_D
model_type: UIP
model_params: 86_589_068
n_estimators: 1

# removed sAlex from this list since it would be double counting materials in the "Training Size"
# metrics table column since OMat24 is a derivative of Alexandria
training_set: [OMat24, MPtrj]

hyperparams:
  max_force: 0.02
  max_steps: 500
  ase_optimizer: FIRE
  loss: MAE
  loss_weights:
    energy: 20
    forces: 10
    stress: 1
  optimizer: AdamW
  learning_rate_schedule: Cosine
  warmup_epochs: 0.1
  warmup_factor: 0.2
  max_learning_rate: 0.0002
  min_learning_rate_factor: 0.01
  grad_clip_threshold: 100
  ema_decay: 0.999
  weight_decay: 0.001
  dropout_rate: 0.1
  stochastic_depth: 0.1
  batch_size: 256
  epochs: 16
  # train_config_url: #TODO add URL

notes:
  Description: |
    EquiformerV2 is an equivariant transformer that uses graph attention, attention re-normalization, and separable S^2 activations and layer normalization.
  Training: |
    Training was done by fine-tuning a model pretrained for 2 epochs on the OMat24 dataset.
