model_name: ORB MPtrj
model_version: v2
matbench_discovery_version: 1.3.1
date_added: "2024-10-14"
date_published: "2024-10-29"
authors:
  - name: Mark Neumann
    affiliation: Orbital Materials
    email: mark@orbitalmaterials.com
    corresponding: true
  - name: Jonathan Godwin
    affiliation: Orbital Materials
    email: jonathan@orbitalmaterials.com
    corresponding: true
  - name: James Gin-Pollock
    affiliation: Orbital Materials
  - name: Zhiyi Li
    affiliation: Orbital Materials
  - name: Ben Rhodes
    affiliation: Orbital Materials
  - name: Hitarth Choubisa
    affiliation: Orbital Materials
  - name: Steven Bennett
    affiliation: Orbital Materials
  - name: Arthur Hussey
    affiliation: Orbital Materials

repo: https://github.com/orbital-materials/orb-models
url: https://orbitalmaterials.com/post/technical-blog-introducing-the-orb-ai-based-interatomic-potential
doi: https://doi.org/10.48550/arXiv.2410.22570
paper: https://arxiv.org/abs/2410.22570

openness: OSOD
trained_for_benchmark: true
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_D
model_type: UIP
model_params: 25_161_727
n_estimators: 1

hyperparams:
  max_force: 0.02
  max_steps: 500
  ase_optimizer: FIRE
  optimizer: Adam
  loss: MAE
  loss_weights: { energy: 10.0, force: 1.0, stress: 1.0 }
  batch_size: 300 # (avg, as batch size is dynamic)
  initial_learning_rate: 0.0003
  learning_rate_schedule: CosineAnnealingLR(T_max=100)
  gradient_clip: 0.5
  ema_decay: 0.999
  n_layers: 15
  features: 256 latent dim, 512 MLP dim
  num_rbfs: 50
  radial_cutoff: 10.0 # Å
  max_num_neighbors: 20

requirements: # strongly recommended
  orb-models: "0.4.0"
  pynanoflann: "pynanoflann@git+https://github.com/dwastberg/pynanoflann#egg=af434039ae14bedcbb838a7808924d6689274168"

training_set: [MPtrj]

notes:
  Description: |
    ORB is a pretrained model for atomic simulations. This model is pretrained and fine-tuned on MPtrj only.

metrics:
  phonons:
    κ_SRME: 1.725
  geo_opt:
    pred_file: models/orb/orb-mptrj-only-v2-20241014.json.gz
    pred_col: orb_structure
  discovery:
    pred_file: models/orb/orbff-mptrj-only-v2-20241014.csv.gz
    pred_col: e_form_per_atom_orb
    full_test_set:
      F1: 0.755
      DAF: 4.188
      Precision: 0.719
      Recall: 0.795
      Accuracy: 0.911
      TPR: 0.795
      FPR: 0.064
      TNR: 0.936
      FNR: 0.205
      TP: 35047.0
      FP: 13729.0
      TN: 199142.0
      FN: 9045.0
      MAE: 0.043
      RMSE: 0.09
      R2: 0.752
      missing_preds: 2
      missing_percent: 0.00%
    most_stable_10k:
      F1: 0.971
      DAF: 6.173
      Precision: 0.944
      Recall: 1.0
      Accuracy: 0.944
      TPR: 1.0
      FPR: 1.0
      TNR: 0.0
      FNR: 0.0
      TP: 9437.0
      FP: 563.0
      TN: 0.0
      FN: 0.0
      MAE: 0.037
      RMSE: 0.098
      R2: 0.801
      missing_preds: 0
      missing_percent: 0.00%
    unique_prototypes:
      F1: 0.765
      DAF: 4.702
      Precision: 0.719
      Recall: 0.817
      Accuracy: 0.922
      TPR: 0.817
      FPR: 0.059
      TNR: 0.941
      FNR: 0.183
      TP: 27276.0
      FP: 10668.0
      TN: 171446.0
      FN: 6098.0
      MAE: 0.045
      RMSE: 0.091
      R2: 0.756
      missing_preds: 0
      missing_percent: 0.00%
