model_name: ORB MPtrj
model_key: orb-mptrj
model_version: v2
matbench_discovery_version: 1.3.1
date_added: "2024-10-14"
date_published: "2024-10-29"
authors:
  - name: Mark Neumann
    affiliation: Orbital Materials
    email: mark@orbitalmaterials.com
    corresponding: true
  - name: Jonathan Godwin
    affiliation: Orbital Materials
    email: jonathan@orbitalmaterials.com
    corresponding: true
  - name: James Gin-Pollock
    affiliation: Orbital Materials
  - name: Zhiyi Li
    affiliation: Orbital Materials
  - name: Ben Rhodes
    affiliation: Orbital Materials
  - name: Hitarth Choubisa
    affiliation: Orbital Materials
  - name: Steven Bennett
    affiliation: Orbital Materials
  - name: Arthur Hussey
    affiliation: Orbital Materials

repo: https://github.com/orbital-materials/orb-models
url: https://orbitalmaterials.com/post/technical-blog-introducing-the-orb-ai-based-interatomic-potential
doi: https://doi.org/10.48550/arXiv.2410.22570
paper: https://arxiv.org/abs/2410.22570
pr_url: https://github.com/janosh/matbench-discovery/pull/133

openness: OSOD
trained_for_benchmark: true
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_D
model_type: UIP
model_params: 25_161_727
n_estimators: 1

hyperparams:
  max_force: 0.02
  max_steps: 500
  ase_optimizer: FIRE
  cell_filter: FrechetCellFilter
  optimizer: Adam
  loss: MAE
  loss_weights:
    energy: 10.0
    force: 1.0
    stress: 1.0
  batch_size: 300 # (avg, as batch size is dynamic)
  initial_learning_rate: 0.0003
  learning_rate_schedule: CosineAnnealingLR(T_max=100)
  gradient_clip: 0.5
  ema_decay: 0.999
  n_layers: 15
  features: 256 latent dim, 512 MLP dim
  num_rbfs: 50
  radial_cutoff: 10.0 # Å
  max_num_neighbors: 20

requirements: # strongly recommended
  orb-models: "0.4.0"
  pynanoflann: "pynanoflann@git+https://github.com/dwastberg/pynanoflann#egg=af434039ae14bedcbb838a7808924d6689274168"

training_set: [MPtrj]

notes:
  Description: |
    ORB is a pretrained model for atomic simulations. This model is pretrained and fine-tuned on MPtrj only.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 1.725
      pred_file: models/orb/orbff-mptrj-v2/2024-11-09-kappa-103-FIRE-dist=0.01-fmax=1e-4-symprec=1e-5.json.gz
      pred_file_url: https://figshare.com/files/52134890
  geo_opt:
    pred_file: models/orb/orbff-mptrj-v2/2024-10-14-wbm-geo-opt.jsonl.gz
    pred_file_url: https://figshare.com/files/52062317
    struct_col: orb_structure
    symprec=1e-5:
      rmsd: 0.0185 # Å
      n_sym_ops_mae: 10.036 # unitless
      symmetry_decrease: 0.8594 # fraction
      symmetry_match: 0.1397 # fraction
      symmetry_increase: 0.0007 # fraction
      n_structures: 256963 # count
      analysis_file: models/orb/orbff-mptrj-v2/2024-10-14-wbm-geo-opt-symprec=1e-5.csv.gz
      analysis_file_url: https://figshare.com/files/52062386
    symprec=1e-2:
      rmsd: 0.0185 # Å
      n_sym_ops_mae: 6.1283 # unitless
      symmetry_decrease: 0.586 # fraction
      symmetry_match: 0.3716 # fraction
      symmetry_increase: 0.0332 # fraction
      n_structures: 256614 # count
      analysis_file: models/orb/orbff-mptrj-v2/2024-10-14-wbm-geo-opt-symprec=1e-2.csv.gz
      analysis_file_url: https://figshare.com/files/52062389
  discovery:
    pred_file: models/orb/orbff-mptrj-v2/2024-10-14-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/files/52057565
    pred_col: e_form_per_atom_orb
    full_test_set:
      F1: 0.755 # fraction
      DAF: 4.188 # dimensionless
      Precision: 0.719 # fraction
      Recall: 0.795 # fraction
      Accuracy: 0.911 # fraction
      TPR: 0.795 # fraction
      FPR: 0.064 # fraction
      TNR: 0.936 # fraction
      FNR: 0.205 # fraction
      TP: 35047.0 # count
      FP: 13729.0 # count
      TN: 199142.0 # count
      FN: 9045.0 # count
      MAE: 0.043 # eV/atom
      RMSE: 0.09 # eV/atom
      R2: 0.752 # dimensionless
      missing_preds: 2 # count
      missing_percent: 0.00% # fraction
    most_stable_10k:
      F1: 0.971 # fraction
      DAF: 6.173 # dimensionless
      Precision: 0.944 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.944 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9437.0 # count
      FP: 563.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.037 # eV/atom
      RMSE: 0.098 # eV/atom
      R2: 0.801 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
    unique_prototypes:
      F1: 0.765 # fraction
      DAF: 4.702 # dimensionless
      Precision: 0.719 # fraction
      Recall: 0.817 # fraction
      Accuracy: 0.922 # fraction
      TPR: 0.817 # fraction
      FPR: 0.059 # fraction
      TNR: 0.941 # fraction
      FNR: 0.183 # fraction
      TP: 27276.0 # count
      FP: 10668.0 # count
      TN: 171446.0 # count
      FN: 6098.0 # count
      MAE: 0.045 # eV/atom
      RMSE: 0.091 # eV/atom
      R2: 0.756 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
