model_name: ORB v2
model_key: orb-v2
model_version: v2
matbench_discovery_version: 1.3.1
date_added: "2024-10-11"
date_published: "2024-10-29"
authors:
  - name: Mark Neumann
    affiliation: Orbital Materials
    email: mark@orbitalmaterials.com
    corresponding: true
  - name: Jonathan Godwin
    affiliation: Orbital Materials
    email: jonathan@orbitalmaterials.com
    corresponding: true
  - name: James Gin-Pollock
    affiliation: Orbital Materials
  - name: Zhiyi Li
    affiliation: Orbital Materials
  - name: Ben Rhodes
    affiliation: Orbital Materials
  - name: Hitarth Choubisa
    affiliation: Orbital Materials
  - name: Steven Bennett
    affiliation: Orbital Materials
  - name: Arthur Hussey
    affiliation: Orbital Materials

repo: https://github.com/orbital-materials/orb-models
url: https://orbitalmaterials.com/post/technical-blog-introducing-the-orb-ai-based-interatomic-potential
doi: https://doi.org/10.48550/arXiv.2410.22570
paper: https://arxiv.org/abs/2410.22570
pr_url: https://github.com/janosh/matbench-discovery/pull/133
# v1 checkpoint: https://storage.googleapis.com/orbitalmaterials-public-models/forcefields/orbff-v1-20240827.ckpt
# v2 URL taken from: https://github.com/orbital-materials/orb-models/blob/637a98d49c/MODELS.md
checkpoint_url: https://orbitalmaterials-public-models.s3.us-west-1.amazonaws.com/forcefields/orb-v2-20241011.ckpt

license:
  code: Apache-2.0
  code_url: https://github.com/orbital-materials/orb-models/blob/637a98d49/LICENSE
  checkpoint: Apache-2.0
  checkpoint_url: https://github.com/orbital-materials/orb-models/blob/637a98d49/LICENSE

openness: OSCD
trained_for_benchmark: false
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_D
model_type: UIP
model_params: 25_161_727
n_estimators: 1

hyperparams:
  max_force: 0.02
  max_steps: 500
  ase_optimizer: FIRE
  cell_filter: FrechetCellFilter
  optimizer: Adam
  loss: MAE
  loss_weights:
    energy: 10.0
    force: 1.0
    stress: 1.0
  batch_size: 300 # (avg, as batch size is dynamic)
  initial_learning_rate: 0.0003
  learning_rate_schedule: CosineAnnealingLR(T_max=100)
  gradient_clip: 0.5
  ema_decay: 0.999
  n_layers: 15
  features: 256 latent dim, 512 MLP dim
  num_rbfs: 50
  radial_cutoff: 10.0 # Å
  max_num_neighbors: 20

requirements: # strongly recommended
  orb-models: "0.4.0"
  pynanoflann: "pynanoflann@git+https://github.com/dwastberg/pynanoflann#egg=af434039ae14bedcbb838a7808924d6689274168"

training_set: [MPtrj, Alex]
training_cost: missing

notes:
  Description: |
    ORB is a pretrained model for atomic simulations. ORB uses a pretrained diffusion model backbone which is fine-tuned on MPtrj + Alexandria.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 1.732
      pred_file: models/orb/orbff-v2/2024-11-09-kappa-103-FIRE-dist=0.01-fmax=1e-4-symprec=1e-5.json.gz
      pred_file_url: https://figshare.com/files/52134887
  geo_opt:
    pred_file: models/orb/orbff-v2/2024-10-11-wbm-geo-opt.jsonl.gz
    pred_file_url: https://figshare.com/files/52062194
    struct_col: orb_structure
    symprec=1e-5:
      rmsd: 0.0973 # unitless
      n_sym_ops_mae: 9.9331 # unitless
      symmetry_decrease: 0.8531 # fraction
      symmetry_match: 0.1433 # fraction
      symmetry_increase: 0.0034 # fraction
      n_structures: 256963 # count
      analysis_file: models/orb/orbff-v2/2024-10-11-wbm-geo-opt-symprec=1e-5-moyo=0.4.2.csv.gz
      analysis_file_url: https://figshare.com/files/53504681
    symprec=1e-2:
      rmsd: 0.0973 # unitless
      n_sym_ops_mae: 5.0639 # unitless
      symmetry_decrease: 0.4547 # fraction
      symmetry_match: 0.4926 # fraction
      symmetry_increase: 0.0453 # fraction
      n_structures: 256963 # count
      analysis_file: models/orb/orbff-v2/2024-10-11-wbm-geo-opt-symprec=1e-2-moyo=0.4.2.csv.gz
      analysis_file_url: https://figshare.com/files/53504684
  discovery:
    pred_file: models/orb/orbff-v2/2024-10-11-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/files/52057562
    pred_col: e_form_per_atom_orb
    full_test_set:
      F1: 0.858 # fraction
      DAF: 5.281 # dimensionless
      Precision: 0.906 # fraction
      Recall: 0.815 # fraction
      Accuracy: 0.954 # fraction
      TPR: 0.815 # fraction
      FPR: 0.017 # fraction
      TNR: 0.983 # fraction
      FNR: 0.185 # fraction
      TP: 35949.0 # count
      FP: 3725.0 # count
      TN: 209146.0 # count
      FN: 8143.0 # count
      MAE: 0.028 # eV/atom
      RMSE: 0.078 # eV/atom
      R2: 0.814 # dimensionless
      missing_preds: 2 # count
      missing_percent: 0.00% # fraction
    most_stable_10k:
      F1: 0.985 # fraction
      DAF: 6.348 # dimensionless
      Precision: 0.97 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.97 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9704.0 # count
      FP: 296.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.068 # eV/atom
      R2: 0.897 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
    unique_prototypes:
      F1: 0.88 # fraction
      DAF: 6.041 # dimensionless
      Precision: 0.924 # fraction
      Recall: 0.841 # fraction
      Accuracy: 0.965 # fraction
      TPR: 0.841 # fraction
      FPR: 0.013 # fraction
      TNR: 0.987 # fraction
      FNR: 0.159 # fraction
      TP: 28055.0 # count
      FP: 2323.0 # count
      TN: 179791.0 # count
      FN: 5319.0 # count
      MAE: 0.028 # eV/atom
      RMSE: 0.077 # eV/atom
      R2: 0.824 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
