model_name: ORB
model_version: v1
matbench_discovery_version: 1.2.0
date_added: "2024-09-02" # required
date_published: "2024-09-02" # Update when paper published
authors: # required (only name, other keys are optional)
  - name: Mark Neumann
    affiliation: Orbital Materials
    email: mark@orbitalmaterials.com
    corresponding: True
  - name: Jonathan Godwin
    affiliation: Orbital Materials
    email: jonathan@orbitalmaterials.com
    corresponding: True
  - name: James Gin-Pollock
    affiliation: Orbital Materials
  - name: Zhiyi Li
    affiliation: Orbital Materials
  - name: Ben Rhodes
    affiliation: Orbital Materials
  - name: Hitarth Choubisa
    affiliation: Orbital Materials
  - name: Steven Bennett
    affiliation: Orbital Materials
  - name: Arthur Hussey
    affiliation: Orbital Materials

repo: https://github.com/orbital-materials/orb-models/
url: <TBD>
doi: <TBD>
paper: <TBD>

openness: OSCD
trained_for_benchmark: false
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS
model_type: UIP
model_params: 25_161_727
n_estimators: 1

hyperparams:
  max_force: 0.02
  max_steps: 500
  ase_optimizer: FIRE
  optimizer: Adam
  loss: MAE
  loss_weights: { energy: 10.0, force: 1.0, stress: 1.0 }
  batch_size: 300 # (avg, as batch size is dynamic)
  initial_learning_rate: 0.0003
  learning_rate_schedule: CosineAnnealingLR(T_max=100)
  gradient_clip: 0.5
  ema_decay: 0.999
  n_layers: 15
  features: 256 latent dim, 512 MLP dim
  num_rbfs: 50
  radial_cutoff: 10.0 # Å
  max_num_neighbors: 20

requirements: # strongly recommended
  orb-models: 0.1
  pynanoflann: "pynanoflann@git+https://github.com/dwastberg/pynanoflann#egg=af434039ae14bedcbb838a7808924d6689274168"

training_set:
  title: MPtrj + Alexandria
  url: https://alexandria.icams.rub.de/ # fix when #132 merged
  n_structures: 32_078023
  n_materials: 3_245_923
  # TODO: Restore after https://github.com/janosh/matbench-discovery/pull/132
  # - title: MPtrj
  #   url: https://figshare.com/articles/dataset/23713842
  #   n_structures: 1_580_395
  #   n_materials: 145_923
  # - title: Alexandria
  #   url: https://alexandria.icams.rub.de/
  #   n_structures: 30_497_628  # (subsampled)
  #   n_materials: 3_100_000

notes: # notes can have any key, be multiline and support markdown.
  description: |
    ORB is a pretrained model for atomic simulations. ORB uses a pretrained diffusion model backbone which is fine-tuned on MPtrj + Alexandria.
