model_name: MatterSim
model_version: n/a
matbench_discovery_version: 1.0.0
date_added: "2024-06-16"
date_published: "2024-05-08"
authors:
  - name: Han Yang
    affiliation: Microsoft Research AI for Science
    email: hanyang@microsoft.com
    orcid: https://orcid.org/0000-0002-4531-093X
  - name: Chenxi Hu
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0009-0006-8486-9230
  - name: Yichi Zhou
    affiliation: Microsoft Research AI for Science
  - name: Xixian Liu
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0009-0008-9215-3990
  - name: Yu Shi
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0001-9235-8963
  - name: Jielan Li
    affiliation: Microsoft Research AI for Science
    email: jielanli@microsoft.com
  - name: Guanzhi Li
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0002-4167-6432
  - name: Zekun Chen
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0002-4183-2941
  - name: Shuizhou Chen
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0009-0005-2701-5565
  - name: Claudio Zeni
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0002-6334-2679
  - name: Matthew Horton
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0001-7777-8871
  - name: Robert Pinsler
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0003-1454-188X
  - name: Andrew Fowler
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0002-7360-3078
  - name: Daniel Zügner
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0003-1626-5065
  - name: Tian Xie
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0002-0987-4666
  - name: Jake Smith
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0003-0412-1312
  - name: Lixin Sun
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0002-7971-5222
  - name: Qian Wang
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0009-0007-7680-4514
  - name: Lingyu Kong
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0009-0006-2226-5730
  - name: Chang Liu
    affiliation: Microsoft Research AI for Science
    orcid: https://orcid.org/0000-0001-5207-5440
  - name: Hongxia Hao
    affiliation: Microsoft Research AI for Science
    email: hongxiahao@microsoft.com
    orcid: https://orcid.org/0000-0002-4382-200X
  - name: Ziheng Lu
    affiliation: Microsoft Research AI for Science
    email: zihenglu@microsoft.com
    orcid: https://orcid.org/0000-0003-2239-8526
repo: https://github.com/microsoft/Graphormer
doi: https://doi.org/10.48550/arXiv.2405.04967
paper: https://arxiv.org/abs/2405.04967

requirements:
  Graphormer: v1
  numpy: 1.26.2
  pymatgen: 2024.5.1

openness: CSCD
trained_for_benchmark: false
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_D
model_type: UIP
model_params: 182_000_000
n_estimators: 1

training_set: [MatterSim]

hyperparams:
  optimizer: AdamW
  learning_rate: 2e-4 # initial value, linearly decayed to 0
  batch_size: 256
  n_layers: 5
  n_features: 128 l=0 scalars, 64 l=1 vectors, 32 l=2 tensors
  radial_cutoff: 5.0 # Å

notes:
  Description: Graphormer is a general-purpose deep learning backbone for molecular modeling.
  Training:
    desc: MatterSim was trained on a large, closed dataset covering diverse combinations of 89 elements across many temperature and pressure.
    temperature_range: 0-5000 K
    pressure_range: 0-1000 GPa
  Tested Applications:
    - Energy, force, stress prediction
    - Molecular dynamics simulations
    - Phonons
    - Mechanical properties
    - Free energy and phase diagrams
    - Materials discovery
  Training Data Sources:
    - Materials Project
    - Alexandria dataset
    - newly generated structures and MD trajectories

metrics:
  geo_opt:
    pred_file: null # not (yet) shared by authors
    pred_col: null
  discovery:
    pred_file: models/mattersim/2024-06-16-mattersim-wbm-IS2RE.csv.gz
    pred_col: e_form_per_atom_mattersim
    full_test_set:
      F1: 0.832
      DAF: 4.838
      Precision: 0.83
      Recall: 0.834
      Accuracy: 0.942
      TPR: 0.834
      FPR: 0.035
      TNR: 0.965
      FNR: 0.166
      TP: 36754.0
      FP: 7516.0
      TN: 205355.0
      FN: 7338.0
      MAE: 0.026
      RMSE: 0.079
      R2: 0.809
      missing_preds: 2
      missing_percent: 0.00%
    most_stable_10k:
      F1: 0.989
      DAF: 6.401
      Precision: 0.978
      Recall: 1.0
      Accuracy: 0.978
      TPR: 1.0
      FPR: 1.0
      TNR: 0.0
      FNR: 0.0
      TP: 9785.0
      FP: 215.0
      TN: 0.0
      FN: 0.0
      MAE: 0.02
      RMSE: 0.065
      R2: 0.906
      missing_preds: 0
      missing_percent: 0.00%
    unique_prototypes:
      F1: 0.859
      DAF: 5.646
      Precision: 0.863
      Recall: 0.856
      Accuracy: 0.957
      TPR: 0.856
      FPR: 0.025
      TNR: 0.975
      FNR: 0.144
      TP: 28562.0
      FP: 4531.0
      TN: 177583.0
      FN: 4812.0
      MAE: 0.026
      RMSE: 0.08
      R2: 0.812
      missing_preds: 0
      missing_percent: 0.00%
