model_name: DPA-3.1-3M-FT
model_key: dpa-3.1-3m-ft
model_version: v0.3 # 2025-06-05
date_added: '2025-06-05'
date_published: '2025-06-05'
authors:
  - name: Duo Zhang
    affiliation: AI for Science Institute, Beijing
    orcid: https://orcid.org/0000-0001-9591-2659
  - name: Anyang Peng
    affiliation: AI for Science Institute, Beijing
    orcid: https://orcid.org/0000-0002-0630-2187
  - name: Chun Cai
    affiliation: AI for Science Institute, Beijing
    orcid: https://orcid.org/0000-0001-6242-0439
  - name: Linfeng Zhang
    affiliation: AI for Science Institute, Beijing; DP Technology
    email: linfeng.zhang.zlf@gmail.com
    corresponding: true
  - name: Han Wang
    affiliation: Beijing Institute of Applied Physics and Computational Mathematics (IAPCM)
    email: wang_han@iapcm.ac.cn
    corresponding: true
trained_by:
  - name: Anyang Peng
    affiliation: AI for Science Institute, Beijing
    orcid: https://orcid.org/0000-0002-0630-2187

repo: https://github.com/deepmodeling/deepmd-kit
url: https://github.com/deepmodeling/deepmd-kit
doi: https://arxiv.org/abs/2506.01686
paper: https://arxiv.org/abs/2506.01686
pr_url: https://github.com/janosh/matbench-discovery/pull/264
checkpoint_url: https://figshare.com/files/55141895

license:
  code: LGPL-3.0
  code_url: https://github.com/deepmodeling/deepmd-kit/blob/70bc6d89/LICENSE
  checkpoint: LGPL-3.0
  checkpoint_url: https://github.com/deepmodeling/deepmd-kit/blob/70bc6d89/LICENSE

openness: OSCD
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
model_type: UIP
model_params: 3_268_838
trained_for_benchmark: true
n_estimators: 1

hyperparams:
  max_force: 0.05
  max_steps: 500
  ase_optimizer: FIRE
  cell_filter: ExpCellFilter
  n_layers: 16
  e_rcut: 6.0
  a_rcut: 4.0
  n_dim: 128
  e_dim: 64
  a_dim: 32
  optimizer: Adam
  pretrain:
    loss: MSE
    loss_weights:
      energy: 0.02 -> 1
      force: 1000 -> 100
      virial: 0.02 -> 1
    initial_learning_rate: 0.001
    learning_rate_schedule: ExpLR - start_lr=0.001, decay_steps=5000, stop_lr=0.00001
    training_steps: 4000000
    batch_size: 960 # 120 (gpus) * 8 (batch per gpu) = 960 (total batch size)
    epochs: 23.5
  finetune:
    loss: Huber
    loss_weights:
      energy: 30
      force: 1
      virial: 2.5
    initial_learning_rate: 0.0001
    learning_rate_schedule: ExpLR - start_lr=0.0001, decay_steps=5000, stop_lr=0.000006
    training_steps: 2000000
    batch_size: 256 # 32 (gpus) * 8 (batch per gpu) = 256 (total batch size)
    epochs: 45
  graph_construction_radius: 6.0 # Å
  max_neighbors: .inf

requirements:
  torch: 2.3.1
  torch-geometric: 2.5.2
  ase: 3.23.0
  pymatgen: 2024.6.10
  numpy: 1.26.4

training_set: [OpenLAM]
training_cost: missing

notes:
  Description: |
    DPA3 is an advanced interatomic potential leveraging the message passing architecture, implemented within the DeePMD-kit framework, available on [GitHub](https://github.com/deepmodeling/deepmd-kit/tree/dpa3-alpha).
    Designed as a large atomic model (LAM), DPA3 is tailored to integrate and simultaneously train on datasets from various disciplines, encompassing diverse chemical and materials systems across different research domains.
    Its model design ensures exceptional fitting accuracy and robust generalization both within and beyond the training domain.
    Furthermore, DPA3 maintains energy conservation and respects the physical symmetries of the potential energy surface, making it a dependable tool for a wide range of scientific applications.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 0.4695
      pred_file: models/deepmd/dpa-3.1-3m-ft/2025-06-05-kappa-103-FIRE-dist=0.01-fmax=1e-4-symprec=1e-5.json.gz
      pred_file_url: https://figshare.com/files/55426286
      κ_SRE: 0.3095
  geo_opt:
    pred_file: models/deepmd/dpa-3.1-3m-ft/2025-06-05-wbm-IS2RE-FIRE.jsonl.gz
    struct_col: dp_structure
    pred_file_url: https://figshare.com/files/55410170
    symprec=1e-5:
      rmsd: 0.0693 # unitless
      n_sym_ops_mae: 2.0174 # unitless
      symmetry_decrease: 0.0539 # fraction
      symmetry_match: 0.7274 # fraction
      symmetry_increase: 0.2138 # fraction
      n_structures: 256963 # count
      analysis_file: models/deepmd/dpa-3.1-3m-ft/2025-06-05-wbm-IS2RE-FIRE-symprec=1e-5-moyo=0.4.2.csv.gz
      analysis_file_url: https://figshare.com/files/55410182
    symprec=1e-2:
      rmsd: 0.0693 # unitless
      n_sym_ops_mae: 1.881 # unitless
      symmetry_decrease: 0.0502 # fraction
      symmetry_match: 0.8109 # fraction
      symmetry_increase: 0.1317 # fraction
      n_structures: 256963 # count
      analysis_file: models/deepmd/dpa-3.1-3m-ft/2025-06-05-wbm-IS2RE-FIRE-symprec=1e-2-moyo=0.4.2.csv.gz
      analysis_file_url: https://figshare.com/files/55410185
  discovery:
    pred_file: models/deepmd/dpa-3.1-3m-ft/2025-06-05-dpa-3.1-3m-ft-preds.csv.gz
    pred_file_url: https://figshare.com/files/55410167
    pred_col: e_form_per_atom_dp
    full_test_set:
      F1: 0.864 # fraction
      DAF: 4.912 # dimensionless
      Precision: 0.843 # fraction
      Recall: 0.887 # fraction
      Accuracy: 0.952 # fraction
      TPR: 0.887 # fraction
      FPR: 0.034 # fraction
      TNR: 0.966 # fraction
      FNR: 0.113 # fraction
      TP: 39116.0 # count
      FP: 7298.0 # count
      TN: 205573.0 # count
      FN: 4976.0 # count
      MAE: 0.022 # eV/atom
      RMSE: 0.067 # eV/atom
      R2: 0.862 # dimensionless
      missing_preds: 2 # count
    most_stable_10k:
      F1: 0.987 # fraction
      DAF: 6.369 # dimensionless
      Precision: 0.974 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.974 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9737.0 # count
      FP: 263.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.067 # eV/atom
      R2: 0.901 # dimensionless
      missing_preds: 0 # count
    unique_prototypes:
      F1: 0.884 # fraction
      DAF: 5.667 # dimensionless
      Precision: 0.866 # fraction
      Recall: 0.903 # fraction
      Accuracy: 0.963 # fraction
      TPR: 0.903 # fraction
      FPR: 0.026 # fraction
      TNR: 0.974 # fraction
      FNR: 0.097 # fraction
      TP: 30139.0 # count
      FP: 4650.0 # count
      TN: 177464.0 # count
      FN: 3235.0 # count
      MAE: 0.023 # eV/atom
      RMSE: 0.067 # eV/atom
      R2: 0.869 # dimensionless
      missing_preds: 0 # count
