model_name: SevenNet-0
model_key: sevennet-0
model_version: v0.9.1_w_cutoff # 2024-07-11
matbench_discovery_version: 1.1.2
date_added: "2024-07-13"
date_published: "2024-02-06"
authors:
  - name: Yutack Park
    affiliation: Seoul National University
    email: parkyutack@snu.ac.kr
    orcid: https://orcid.org/0009-0008-8690-935X
  - name: Jaesun Kim
    affiliation: Seoul National University
    orcid: https://orcid.org/0009-0000-6646-1318
  - name: Seungwoo Hwang
    affiliation: Seoul National University
    orcid: https://orcid.org/0000-0002-1523-8340
  - name: Seungwu Han
    affiliation: Seoul National University, Korea Institute for Advanced Study
    email: hansw@snu.ac.kr
    orcid: https://orcid.org/0000-0003-3958-0922
    corresponding: true
trained_by:
  - name: Saerom Choi
    affiliation: Samsung Advanced Institute of Technology, Seoul National University
    orcid: https://orcid.org/0009-0004-2240-5428

repo: https://github.com/MDIL-SNU/SevenNet
url: https://github.com/MDIL-SNU/SevenNet/tree/afb56e10b6/sevenn/pretrained_potentials/SevenNet_0__11July2024
doi: https://doi.org/10.1021/acs.jctc.4c00190
paper: https://arxiv.org/abs/2402.03789
pypi: https://pypi.org/project/sevenn
pr_url: https://github.com/janosh/matbench-discovery/pull/112

openness: OSOD
trained_for_benchmark: false
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
model_type: UIP
model_params: 842_440
n_estimators: 1

hyperparams:
  max_force: 0.05
  max_steps: 500
  ase_optimizer: FIRE
  optimizer: Adam
  loss: Huber - delta=0.01
  loss_weights:
    energy: 1.0
    force: 1.0
    stress: 0.01
  batch_size: 4096 # 32 (gpus) * 128 (batch per gpu) = 4096 (total batch size)
  initial_learning_rate: 0.010
  learning_rate_schedule: LinearLR - start_factor=1.0, total_iters=600, end_factor=0.0001
  epochs: 600
  n_layers: 5
  n_features: 128 l=0 scalars, 64 l=1 vectors, 32 l=2 tensors
  n_radial_bessel_basis: 8
  radial_cutoff: 5.0 # Å
  sph_harmonics_l_max: 2

requirements:
  torch: 2.2.1
  torch-geometric: 2.5.2
  torch_scatter: 2.1.2
  ase: 3.22.1
  pymatgen: 2024.6.10
  numpy: 1.26.4

training_set: [MPtrj]

notes:
  Description: |
    SevenNet is a graph neural network interatomic potential package that supports parallel molecular dynamics simulations.
    In the SevenNet-0 model, based on the NequIP architecture, the tensor product in the self-connection layer, which includes numerous element-specific parameters, is replaced by a linear (or self-interaction) layer, this reduces the number of parameters from 16_240_000 (c.f. GNoME) to 842_440.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 0.767
      pred_file: models/sevennet/sevennet-0/2024-11-09-kappa-103-FIRE-dist=0.01-fmax=1e-4-symprec=1e-5.json.gz
      pred_file_url: https://figshare.com/ndownloader/files/52134878
  geo_opt:
    pred_file: models/sevennet/sevennet-0/2024-07-11-wbm-geo-opt.json.gz
    pred_file_url: https://figshare.com/ndownloader/files/52062035
    struct_col: sevennet_structure
    symprec=1e-5:
      rmsd: 0.0193 # Å
      n_sym_ops_mae: 2.5921 # unitless
      symmetry_decrease: 0.3557 # fraction
      symmetry_match: 0.4535 # fraction
      symmetry_increase: 0.1446 # fraction
      n_structures: 256963 # count
      analysis_file: models/sevennet/sevennet-0/2024-07-11-wbm-geo-opt-symprec=1e-5.csv.gz
      analysis_file_url: https://figshare.com/ndownloader/files/52062041
    symprec=1e-2:
      rmsd: 0.0193 # Å
      n_sym_ops_mae: 1.9558 # unitless
      symmetry_decrease: 0.0831 # fraction
      symmetry_match: 0.7823 # fraction
      symmetry_increase: 0.1262 # fraction
      n_structures: 256614 # count
      analysis_file: models/sevennet/sevennet-0/2024-07-11-wbm-geo-opt-symprec=1e-2.csv.gz
      analysis_file_url: https://figshare.com/ndownloader/files/52062050
  discovery:
    pred_file: models/sevennet/sevennet-0/2024-07-11-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/ndownloader/files/52057544
    pred_col: e_form_per_atom_sevennet
    full_test_set:
      F1: 0.719 # fraction
      DAF: 3.804 # dimensionless
      Precision: 0.653 # fraction
      Recall: 0.8 # fraction
      Accuracy: 0.893 # fraction
      TPR: 0.8 # fraction
      FPR: 0.088 # fraction
      TNR: 0.912 # fraction
      FNR: 0.2 # fraction
      TP: 35259.0 # count
      FP: 18765.0 # count
      TN: 194106.0 # count
      FN: 8833.0 # count
      MAE: 0.046 # eV/atom
      RMSE: 0.09 # eV/atom
      R2: 0.75 # dimensionless
      missing_preds: 3 # count
      missing_percent: 0.00% # fraction
    most_stable_10k:
      F1: 0.945 # fraction
      DAF: 5.857 # dimensionless
      Precision: 0.895 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.895 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 8954.0 # count
      FP: 1046.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.054 # eV/atom
      RMSE: 0.124 # eV/atom
      R2: 0.7 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
    unique_prototypes:
      F1: 0.724 # fraction
      DAF: 4.252 # dimensionless
      Precision: 0.65 # fraction
      Recall: 0.818 # fraction
      Accuracy: 0.904 # fraction
      TPR: 0.818 # fraction
      FPR: 0.081 # fraction
      TNR: 0.919 # fraction
      FNR: 0.182 # fraction
      TP: 27304.0 # count
      FP: 14703.0 # count
      TN: 167411.0 # count
      FN: 6070.0 # count
      MAE: 0.048 # eV/atom
      RMSE: 0.092 # eV/atom
      R2: 0.75 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
