model_name: SevenNet-MF-ompa
model_key: sevennet-mf-ompa
model_version: v0.11.0 # 2024-07-11
matbench_discovery_version: 1.1.2
date_added: "2025-03-13"
date_published: "2025-03-13"
authors:
  - name: Jaesun Kim
    affiliation: Seoul National University
    orcid: https://orcid.org/0009-0000-6646-1318
  - name: Jisu Kim
    affiliation: Seoul National University
    orcid: https://orcid.org/0009-0000-7380-6089
  - name: Jaehoon Kim
    affiliation: Seoul National University
    orcid: https://orcid.org/0009-0006-3182-9411
  - name: Jiho lee
    affiliation: Seoul National University
    orcid: https://orcid.org/0009-0008-7266-091X
  - name: Yutack Park
    affiliation: Seoul National University
    email: parkyutack@snu.ac.kr
    orcid: https://orcid.org/0009-0008-8690-935X
  - name: Youngho Kang
    affiliation: Incheon National University
    orcid: https://orcid.org/0000-0003-4532-0027
    corresponding: true
  - name: Seungwu Han
    affiliation: Seoul National University, Korea Institute for Advanced Study
    email: hansw@snu.ac.kr
    orcid: https://orcid.org/0000-0003-3958-0922
    corresponding: true
trained_by:
  - name: Jaesun Kim
    affiliation: Seoul National University
    orcid: https://orcid.org/0009-0000-6646-1318

repo: https://github.com/MDIL-SNU/SevenNet
url: https://figshare.com/files/52975859
doi: https://doi.org/10.1021/jacs.4c14455
paper: https://arxiv.org/abs/2409.07947
pypi: https://pypi.org/project/sevenn
pr_url: https://github.com/janosh/matbench-discovery/pull/221

openness: OSOD
trained_for_benchmark: false
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
model_type: UIP
model_params: 25_734_966
n_estimators: 1

hyperparams:
  max_force: 0.02
  max_steps: 800
  ase_optimizer: FIRE
  cell_filter: FrechetCellFilter
  optimizer: Adamw
  loss: MAE/L2MAE/L2MAE
  loss_weights:
    energy: 1.0
    force: 0.1
    stress: 0.0001
  batch_size: 512
  initial_learning_rate: 0.0002
  learning_rate_schedule: LinearLR - start_factor=1.0, total_iters=600, end_factor=0.0001
  epochs: 2
  n_layers: 5
  n_features:
    - 128x0e
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e+64x1o+64x1e+32x2o+32x2e+32x3o+32x3e
    - 128x0o+128x0e+64x1o+64x1e+32x2o+32x2e+32x3o+32x3e
    - 128x0e+64x1o+32x2e+32x3o
    - 128x0e
  n_radial_bessel_basis: 8
  radial_cutoff: 6.0 # Å
  sph_harmonics_l_max: 3

requirements:
  torch: 2.2.1
  torch-geometric: 2.5.2
  ase: 3.22.1
  pymatgen: 2024.6.10
  numpy: 1.26.4

training_set: [OMat24, sAlex, MPtrj]

notes:
  Description: |
    SevenNet is a graph neural network interatomic potential package that supports parallel molecular dynamics simulations. The SevenNet-MF-ompa model used Multi-fidelity learning to simultaneously train on the OMat24, MPtrj, and sAlex datasets, achieving high accuracy despite differences in their DFT calculation settings.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 0.317
      pred_file: models/sevennet/sevennet-mf-ompa/2025-03-11-kappa-103-FIRE-dist=0.03-fmax=1e-4-symprec=1e-5.json.gz
      pred_file_url: https://figshare.com/files/52984310
  geo_opt:
    pred_file: models/sevennet/sevennet-mf-ompa/2025-03-11-wbm-geo-opt-FIRE.json.gz
    pred_file_url: https://figshare.com/files/52983491
    struct_col: sevennet_structure
    symprec=1e-2:
      rmsd: 0.0115 # Å
      n_sym_ops_mae: 1.7053 # unitless
      symmetry_decrease: 0.0467 # fraction
      symmetry_match: 0.8181 # fraction
      symmetry_increase: 0.128 # fraction
      n_structures: 256963 # count
      analysis_file: models/sevennet/sevennet-mf-ompa/2025-03-11-wbm-geo-opt-FIRE-symprec=1e-2-moyo=0.4.2.csv.gz
      analysis_file_url: https://figshare.com/files/53029115
    symprec=1e-5:
      rmsd: 0.0115 # Å
      n_sym_ops_mae: 2.0326 # unitless
      symmetry_decrease: 0.0439 # fraction
      symmetry_match: 0.7057 # fraction
      symmetry_increase: 0.2453 # fraction
      n_structures: 256963 # count
      analysis_file: models/sevennet/sevennet-mf-ompa/2025-03-11-wbm-geo-opt-FIRE-symprec=1e-5-moyo=0.4.2.csv.gz
      analysis_file_url: https://figshare.com/files/53029142
  discovery:
    pred_file: models/sevennet/sevennet-mf-ompa/2025-03-11-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/files/52983488
    pred_col: e_form_per_atom_sevennet
    unique_prototypes:
      F1: 0.901 # fraction
      DAF: 5.825 # dimensionless
      Precision: 0.89 # fraction
      Recall: 0.911 # fraction
      Accuracy: 0.969 # fraction
      TPR: 0.911 # fraction
      FPR: 0.021 # fraction
      TNR: 0.979 # fraction
      FNR: 0.089 # fraction
      TP: 30401.0 # count
      FP: 3739.0 # count
      TN: 178375.0 # count
      FN: 2973.0 # count
      MAE: 0.021 # eV/atom
      RMSE: 0.067 # eV/atom
      R2: 0.867 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
    full_test_set:
      F1: 0.884 # fraction
      DAF: 5.082 # dimensionless
      Precision: 0.872 # fraction
      Recall: 0.895 # fraction
      Accuracy: 0.96 # fraction
      TPR: 0.895 # fraction
      FPR: 0.027 # fraction
      TNR: 0.973 # fraction
      FNR: 0.105 # fraction
      TP: 39484.0 # count
      FP: 5799.0 # count
      TN: 207072.0 # count
      FN: 4608.0 # count
      MAE: 0.021 # eV/atom
      RMSE: 0.067 # eV/atom
      R2: 0.861 # dimensionless
      missing_preds: 2 # count
      missing_percent: 0.00% # fraction
    most_stable_10k:
      F1: 0.985 # fraction
      DAF: 6.346 # dimensionless
      Precision: 0.97 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.97 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9701.0 # count
      FP: 299.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.071 # eV/atom
      R2: 0.888 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
