model_name: SevenNet-l3i5
model_key: sevennet-l3i5
model_version: v0.10.3 # 2024-07-11
matbench_discovery_version: 1.1.2
date_added: "2024-12-10"
date_published: "2024-02-06"
authors:
  - name: Yutack Park
    affiliation: Seoul National University
    email: parkyutack@snu.ac.kr
    orcid: https://orcid.org/0009-0008-8690-935X
  - name: Jaesun Kim
    affiliation: Seoul National University
    orcid: https://orcid.org/0009-0000-6646-1318
  - name: Seungwoo Hwang
    affiliation: Seoul National University
    orcid: https://orcid.org/0000-0002-1523-8340
  - name: Seungwu Han
    affiliation: Seoul National University, Korea Institute for Advanced Study
    email: hansw@snu.ac.kr
    orcid: https://orcid.org/0000-0003-3958-0922
    corresponding: true
trained_by:
  - name: Saerom Choi
    affiliation: Samsung Advanced Institute of Technology, Seoul National University
    orcid: https://orcid.org/0009-0004-2240-5428

repo: https://github.com/MDIL-SNU/SevenNet
url: https://github.com/MDIL-SNU/SevenNet/blob/main/sevenn/pretrained_potentials/SevenNet_l3i5
doi: https://doi.org/10.1021/acs.jctc.4c00190
paper: https://arxiv.org/abs/2402.03789
pypi: https://pypi.org/project/sevenn
pr_url: https://github.com/janosh/matbench-discovery/pull/172

openness: OSOD
trained_for_benchmark: false
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
model_type: UIP
model_params: 1_171_144
n_estimators: 1

hyperparams:
  max_force: 0.05
  max_steps: 500
  ase_optimizer: FIRE
  optimizer: Adam
  loss: Huber - delta=0.01
  loss_weights:
    energy: 1.0
    force: 1.0
    stress: 0.01
  batch_size: 1024 # 32 (gpus) * 32 (batch per gpu) = 1024 (total batch size)
  initial_learning_rate: 0.010
  learning_rate_schedule: LinearLR - start_factor=1.0, total_iters=600, end_factor=0.0001
  epochs: 600
  n_layers: 5
  n_features: 128 l=0 scalars, 64 l=1 vectors, 32 l=2 tensors, 32 l=3 tensors
  n_radial_bessel_basis: 8
  radial_cutoff: 5.0 # Å
  sph_harmonics_l_max: 3

requirements:
  torch: 2.2.1
  torch-geometric: 2.5.2
  ase: 3.22.1
  pymatgen: 2024.6.10
  numpy: 1.26.4

training_set: [MPtrj]

notes:
  Description: |
    SevenNet is a graph neural network interatomic potential package that supports parallel molecular dynamics simulations.
    In the SevenNet-l3i5 model, based on the NequIP architecture, the self-connection layer is replaced by a linear (or self-interaction) layer removing numerous element-dependent parameters. Compared to the SevenNet-0, which uses spherical harmonics up to l=2, SevenNet-l3i5 employs l=3 resulting in higher accuracy.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 0.550
      pred_file: models/sevennet/sevennet-l3i5/2024-12-10-kappa-103-FIRE-dist=0.01-fmax=1e-4-symprec=1e-5.json.gz
      pred_file_url: https://figshare.com/ndownloader/files/52134881
  geo_opt:
    pred_file: models/sevennet/sevennet-l3i5/2024-12-10-wbm-geo-opt.json.gz
    pred_file_url: https://figshare.com/ndownloader/files/52062056
    struct_col: sevennet_structures
    symprec=1e-5:
      rmsd: 0.0182 # Å
      n_sym_ops_mae: 2.7288 # unitless
      symmetry_decrease: 0.3602 # fraction
      symmetry_match: 0.4418 # fraction
      symmetry_increase: 0.1498 # fraction
      n_structures: 256963 # count
      analysis_file: models/sevennet/sevennet-l3i5/2024-12-10-wbm-geo-opt-symprec=1e-5.csv.gz
      analysis_file_url: https://figshare.com/ndownloader/files/52062170
    symprec=1e-2:
      rmsd: 0.0182 # Å
      n_sym_ops_mae: 1.9727 # unitless
      symmetry_decrease: 0.0856 # fraction
      symmetry_match: 0.7752 # fraction
      symmetry_increase: 0.1294 # fraction
      n_structures: 256614 # count
      analysis_file: models/sevennet/sevennet-l3i5/2024-12-10-wbm-geo-opt-symprec=1e-2.csv.gz
      analysis_file_url: https://figshare.com/ndownloader/files/52062173
  discovery:
    pred_file: models/sevennet/sevennet-l3i5/2024-12-10-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/ndownloader/files/52057547
    pred_col: e_form_per_atom_chgTot_l3i5
    full_test_set:
      F1: 0.751 # fraction
      DAF: 4.112 # dimensionless
      Precision: 0.706 # fraction
      Recall: 0.803 # fraction
      Accuracy: 0.909 # fraction
      TPR: 0.803 # fraction
      FPR: 0.069 # fraction
      TNR: 0.931 # fraction
      FNR: 0.197 # fraction
      TP: 35385.0 # count
      FP: 14764.0 # count
      TN: 198107.0 # count
      FN: 8707.0 # count
      MAE: 0.042 # eV/atom
      RMSE: 0.086 # eV/atom
      R2: 0.773 # dimensionless
      missing_preds: 3 # count
      missing_percent: 0.00% # fraction
    most_stable_10k:
      F1: 0.952 # fraction
      DAF: 5.945 # dimensionless
      Precision: 0.909 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.909 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9088.0 # count
      FP: 912.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.05 # eV/atom
      RMSE: 0.114 # eV/atom
      R2: 0.745 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
    unique_prototypes:
      F1: 0.76 # fraction
      DAF: 4.629 # dimensionless
      Precision: 0.708 # fraction
      Recall: 0.821 # fraction
      Accuracy: 0.92 # fraction
      TPR: 0.821 # fraction
      FPR: 0.062 # fraction
      TNR: 0.938 # fraction
      FNR: 0.179 # fraction
      TP: 27404.0 # count
      FP: 11322.0 # count
      TN: 170792.0 # count
      FN: 5970.0 # count
      MAE: 0.044 # eV/atom
      RMSE: 0.087 # eV/atom
      R2: 0.776 # dimensionless
      missing_preds: 1 # count
      missing_percent: 0.00% # fraction
