model_name: AlphaNet-v1-MPtrj
model_key: alphanet-v1-mptrj
model_version: v1
date_added: '2025-03-05'
date_published: '2025-03-05'
authors:
  - name: Bangchen Yin
    affiliation: Tsinghua University
    email: yinbc24@mails.tsinghua.edu.cn
  - name: Jiaao Wang
    email: wangjiaao0720@utexas.edu
    affiliation: University of Texas at Austin
    corresponding: true
  - name: Weitao Du
    affiliation: DAMO Academy, Alibaba Inc
    email: duweitao.dwt@alibaba-inc.com
  - name: Yuanqi Du
    affiliation: Cornell University
    email: yd392@cornell.edu
    corresponding: true
  - name: Chenru Duan
    affiliation: Deep Principle
    email: duanchenru@deepprinciple.com
    corresponding: true
  - name: Carla P. Gomes
    affiliation: Cornell University
    email: gomes@cs.cornell.edu
  - name: Graeme Henkelman
    affiliation: The University of Texas at Austin
    email: henkelman@utexas.edu
  - name: Hai Xiao
    affiliation: Tsinghua University
    email: haixiao@tsinghua.edu.cn
    corresponding: true
trained_by:
  - name: Bangchen Yin
    affiliation: Tsinghua University
    email: yinbc24@mails.tsinghua.edu.cn

repo: https://github.com/zmyybc/AlphaNet
url: https://github.com/zmyybc/AlphaNet
pr_url: https://github.com/janosh/matbench-discovery/pull/216
paper: https://arxiv.org/abs/2501.07155
doi: https://doi.org/10.48550/arXiv.2501.07155
# checkpoint page: https://github.com/zmyybc/AlphaNet/blob/243fe71cb96/README.md#pretrained-models
checkpoint_url: https://figshare.com/files/52870784

license:
  code: GPL-3.0
  code_url: https://github.com/zmyybc/AlphaNet/blob/243fe71cb/LICENSE
  checkpoint: CC-BY-4.0
  checkpoint_url: https://figshare.com/articles/dataset/mp-0225-2_ckpt/28560176?file=52870784

openness: OSOD
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
model_type: UIP
model_params: 16234332
trained_for_benchmark: true
n_estimators: 1
status: superseded

hyperparams:
  max_force: 0.05
  max_steps: 500
  ase_optimizer: FIRE
  cell_filter: FrechetCellFilter
  optimizer: Adam
  loss: MAE
  loss_weights:
    energy: 4.0
    force: 100.0
    stress: 10
  batch_size: 128 #(8 per device)
  initial_learning_rate: 0.0002
  learning_rate_schedule: CosineAnnealingLR(Tmax=200, lr_min = 1e-6)
  epochs: 200
  n_layers: 6
  n_hidden_channels: 256
  n_radial_guassian_basis: 256
  n_heads: 24
  graph_construction_radius: 6.0 # Å, from table 6 in arXiv:2501.07155
  max_neighbors: .inf # max_num_neighbors_threshold seems to be unused in https://github.com/zmyybc/AlphaNet/blob/243fe71cb9/alphanet/models/graph.py#L28

requirements:
  torch: 2.5.1
  torch-geometric: 2.6.1
  torch-scatter: 2.1.2+pt25cu121
  ase: 3.24.0
  pymatgen: 2024.6.10
  numpy: 1.26.4

training_set: [MPtrj] #train/valid split: 0.95/0.05
training_cost: missing
notes:
  Description: |
    AlphaNet is a local frame-based equivariant model designed to tackle the challenges of achieving both accurate and efficient simulations for atomistic systems. AlphaNet enhances computational efficiency and accuracy by leveraging the local geometric structures of atomic environments through the construction of equivariant local frames and learnable frame transitions.

metrics:
  phonons:
    kappa_103:
      κ_SRME: 1.310
      pred_file: models/alphanet/mptrj/2025-03-04-kappa-103-fire-dist=0.01-fmax=1e-4-symprec=1e-5.json.gz #find a lots of imag freqs, will look into this in the future
      pred_file_url: https://figshare.com/files/52869011
  geo_opt:
    pred_file: models/alphanet/mptrj/2025-03-04-wbm-geo-opt-fire.jsonl.gz
    pred_file_url: https://figshare.com/files/52858202
    struct_col: alphanet_structure
    symprec=1e-5:
      rmsd: 0.1067 # unitless
      n_sym_ops_mae: 10.1098 # unitless
      symmetry_decrease: 0.8597 # fraction
      symmetry_match: 0.1376 # fraction
      symmetry_increase: 0.0024 # fraction
      n_structures: 256963 # count
      analysis_file: models/alphanet/mptrj/2025-03-04-wbm-geo-opt-fire-symprec=1e-5-moyo=0.4.2.csv.gz
      analysis_file_url: https://figshare.com/files/53504501
    symprec=1e-2:
      rmsd: 0.1067 # unitless
      n_sym_ops_mae: 8.1732 # unitless
      symmetry_decrease: 0.5768 # fraction
      symmetry_match: 0.3712 # fraction
      symmetry_increase: 0.0419 # fraction
      n_structures: 256963 # count
      analysis_file: models/alphanet/mptrj/2025-03-04-wbm-geo-opt-fire-symprec=1e-2-moyo=0.4.2.csv.gz
      analysis_file_url: https://figshare.com/files/53504504
  discovery:
    pred_file: models/alphanet/mptrj/2025-03-04-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/files/52869026
    pred_col: e_form_per_atom_alphanet
    full_test_set:
      F1: 0.789 # fraction
      DAF: 4.312 # dimensionless
      Precision: 0.74 # fraction
      Recall: 0.846 # fraction
      Accuracy: 0.923 # fraction
      TPR: 0.846 # fraction
      FPR: 0.062 # fraction
      TNR: 0.938 # fraction
      FNR: 0.154 # fraction
      TP: 37311.0 # count
      FP: 13119.0 # count
      TN: 199752.0 # count
      FN: 6781.0 # count
      MAE: 0.04 # eV/atom
      RMSE: 0.091 # eV/atom
      R2: 0.747 # dimensionless
      missing_preds: 2 # count
      missing_percent: 0.00% # fraction
    unique_prototypes:
      F1: 0.799 # fraction
      DAF: 4.863 # dimensionless
      Precision: 0.743 # fraction
      Recall: 0.864 # fraction
      Accuracy: 0.933 # fraction
      TPR: 0.864 # fraction
      FPR: 0.055 # fraction
      TNR: 0.945 # fraction
      FNR: 0.136 # fraction
      TP: 28831.0 # count
      FP: 9949.0 # count
      TN: 172165.0 # count
      FN: 4543.0 # count
      MAE: 0.041 # eV/atom
      RMSE: 0.093 # eV/atom
      R2: 0.745 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
    most_stable_10k:
      F1: 0.96 # fraction
      DAF: 6.042 # dimensionless
      Precision: 0.924 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.924 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9237.0 # count
      FP: 763.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.045 # eV/atom
      RMSE: 0.115 # eV/atom
      R2: 0.746 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
  diatomics:
    pred_file: models/alphanet/2025-03-08-diatomics.json.gz
    pred_file_url: https://figshare.com/files/52868972
