model_name: AlphaNet-v1-MPtrj
model_key: alphanet-v1-mptrj
model_version: v1
dates:
  benchmark_added: '2025-03-05'
  paper_published: '2025-03-05'
lifecycle: superseded
superseded_by: alphanet-v1-oam
authors:
  - name: Bangchen Yin
    affiliation: Tsinghua University
    email: yinbc24@mails.tsinghua.edu.cn
  - name: Jiaao Wang
    email: wangjiaao0720@utexas.edu
    affiliation: University of Texas at Austin
    corresponding: true
  - name: Weitao Du
    affiliation: DAMO Academy, Alibaba Inc
    email: duweitao.dwt@alibaba-inc.com
  - name: Yuanqi Du
    affiliation: Cornell University
    email: yd392@cornell.edu
    corresponding: true
  - name: Chenru Duan
    affiliation: Deep Principle
    email: duanchenru@deepprinciple.com
    corresponding: true
  - name: Carla P. Gomes
    affiliation: Cornell University
    email: gomes@cs.cornell.edu
  - name: Graeme Henkelman
    affiliation: The University of Texas at Austin
    email: henkelman@utexas.edu
  - name: Hai Xiao
    affiliation: Tsinghua University
    email: haixiao@tsinghua.edu.cn
    corresponding: true
trained_by:
  - name: Bangchen Yin
    affiliation: Tsinghua University
    email: yinbc24@mails.tsinghua.edu.cn

repo: https://github.com/zmyybc/AlphaNet
doi: https://doi.org/10.48550/arXiv.2501.07155
paper: https://arxiv.org/abs/2501.07155
docs: https://github.com/zmyybc/AlphaNet
pr_url: https://github.com/janosh/matbench-discovery/pull/216
checkpoint_url: https://figshare.com/files/52870784
license:
  code: GPL-3.0
  code_url: https://github.com/zmyybc/AlphaNet/blob/243fe71cb/LICENSE
  checkpoint: CC-BY-4.0
  checkpoint_url: https://figshare.com/articles/dataset/mp-0225-2_ckpt/28560176?file=52870784

environment:
  dependencies:
    - alphanet @ git+https://github.com/zmyybc/AlphaNet
    - torch==2.5.1
    - torch-geometric==2.6.1
    - torch-scatter
    - numpy<2
    - ase==3.24.0
    - pymatgen==2024.6.10
  python_version: '3.12'
  find_links: ['https://data.pyg.org/whl/torch-2.5.1+cu121.html']
openness: OSOD
architecture_types: [gnn]
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
training_sets: [MPtrj]
model_params: 16234332
hyperparams:
  evaluation:
    max_force: 0.05
    max_steps: 500
    ase_optimizer: FIRE
    cell_filter: FrechetCellFilter
    kappa:
      protocol: phonondb-v1
  architecture:
    n_layers: 6
    graph_construction_radius: 6.0
  training:
    batch_size: 128
    initial_learning_rate: 0.0002
    epochs: 200
    optimizer: Adam
  upstream_config:
    loss: MAE
    loss_weights:
      energy: 4.0
      force: 100.0
      stress: 10
    learning_rate_schedule: CosineAnnealingLR(Tmax=200, lr_min = 1e-6)
    n_hidden_channels: 256
    n_radial_gaussian_basis: 256
    n_heads: 24
notes:
  description: |
    AlphaNet is a local frame-based equivariant model designed to tackle the challenges of achieving both accurate and efficient simulations for atomistic systems. AlphaNet enhances computational efficiency and accuracy by leveraging the local geometric structures of atomic environments through the construction of equivariant local frames and learnable frame transitions.

metrics:
  diatomics:
    pred_file:
      name: models/alphanet/alphanet-v1-mptrj/2025-03-08-diatomics.json.gz
      url: https://figshare.com/files/52868972
      size: 250321
      md5: 42d9c254b72e99802d3a34acdc66eb61
    hardware: NVIDIA H200
    run_time_sec: 196.1
    pbe_wall_dist_mae: 0.2832
    pbe_energy_mae: 8.571
    pbe_bond_length_error: 0.5899
    pbe_well_depth_error: 8.938
    pbe_vib_freq_error: 450.0
    tortuosity: 2.491
    energy_diff_flips: 6.909
    energy_jump: 64.18
    force_flips: 6.318
    force_total_variation: 16610.0
    force_jump: 23140.0
    pbe_force_mae: 44.32
  discovery:
    pred_file:
      name: models/alphanet/alphanet-v1-mptrj/2025-03-04-discovery.csv.gz
      url: https://figshare.com/files/66646331
      size: 1321073
      md5: 8bd5c7eb8a016ebb6091f2c86d7c5d71
    full_test_set:
      F1: 0.789  # fraction
      DAF: 4.312 # dimensionless
      Precision: 0.74 # fraction
      Recall: 0.846 # fraction
      Accuracy: 0.923 # fraction
      TPR: 0.846 # fraction
      FPR: 0.062 # fraction
      TNR: 0.938 # fraction
      FNR: 0.154 # fraction
      TP: 37311 # count
      FP: 13119 # count
      TN: 199752 # count
      FN: 6781 # count
      MAE: 0.04 # eV/atom
      RMSE: 0.091 # eV/atom
      R2: 0.747 # dimensionless
      missing_preds: 2 # count
    unique_prototypes:
      F1: 0.799  # fraction
      DAF: 4.863 # dimensionless
      Precision: 0.743 # fraction
      Recall: 0.864 # fraction
      Accuracy: 0.933 # fraction
      TPR: 0.864 # fraction
      FPR: 0.055 # fraction
      TNR: 0.945 # fraction
      FNR: 0.136 # fraction
      TP: 28831 # count
      FP: 9949 # count
      TN: 172165 # count
      FN: 4543 # count
      MAE: 0.041 # eV/atom
      RMSE: 0.093 # eV/atom
      R2: 0.745 # dimensionless
      missing_preds: 0 # count
    most_stable_10k:
      F1: 0.96  # fraction
      DAF: 6.042 # dimensionless
      Precision: 0.924 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.924 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9237 # count
      FP: 763 # count
      TN: 0 # count
      FN: 0 # count
      MAE: 0.045 # eV/atom
      RMSE: 0.115 # eV/atom
      R2: 0.746 # dimensionless
      missing_preds: 0 # count
  geo_opt:
    pred_file:
      name: models/alphanet/alphanet-v1-mptrj/2025-03-04-geo-opt.jsonl.gz
      url: https://figshare.com/files/53153453
      size: 155547890
      md5: 0989b0eb04dbc5682776787725610195
    symprec=1e-5:
      rmsd: 0.1067
      n_sym_ops_mae: 10.1098
      symmetry_decrease: 0.8597
      symmetry_match: 0.1376
      symmetry_increase: 0.0024
      n_structures: 256963
      analysis_file:
        name: models/alphanet/alphanet-v1-mptrj/2025-03-04-geo-opt-symprec=1e-5-moyo=0.4.2.csv.gz
        url: https://figshare.com/files/53504501
        size: 6197042
        md5: 72ff76d1745d8288fc6872427c5fe5be
    symprec=1e-2:
      rmsd: 0.1067
      n_sym_ops_mae: 8.1732
      symmetry_decrease: 0.5768
      symmetry_match: 0.3712
      symmetry_increase: 0.0419
      n_structures: 256963
      analysis_file:
        name: models/alphanet/alphanet-v1-mptrj/2025-03-04-geo-opt-symprec=1e-2-moyo=0.4.2.csv.gz
        url: https://figshare.com/files/53504504
        size: 7355028
        md5: 80e0e4298a9343e7c8525d433afec80f
  phonons:
    kappa_103:
      κ_SRME: 1.3046
      pred_file:
        name: models/alphanet/alphanet-v1-mptrj/2025-03-04-phonons-kappa-103.json.gz
        url: https://figshare.com/files/52869011
        size: 15912336
        md5: ba3105c0bd952dbfcd92d7aea13e0c77
      κ_SRE: 1.178
