model_name: eqV2 S DeNS TraceGrad
model_key: eqV2-s-dens-tracegrad-mp
model_version: v2024.10.18
matbench_discovery_version: 1.3.1
date_added: "2025-04-01"
date_published: "2024-04-01"
authors:
  - name: Luis Barroso-Luque
    affiliation: FAIR Meta
    email: lbluque@meta.com
    orcid: https://orcid.org/0000-0002-6453-9545
    github: https://github.com/lbluque
    corresponding: true
  - name: Muhammed Shuaibi
    affiliation: FAIR Meta

repo: https://github.com/FAIR-Chem/fairchem
doi: https://doi.org/10.48550/arXiv.2410.12771
paper: https://arxiv.org/abs/2410.12771
url: https://huggingface.co/fairchem/OMAT24
pypi: https://pypi.org/project/fairchem-core
pr_url: https://github.com/janosh/matbench-discovery/pull/146

requirements:
  fairchem-core: 1.2.1

openness: OSOD
trained_for_benchmark: true
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_D
model_type: UIP
model_params: 31_207_434 # 31M
n_estimators: 1

training_set: [MPtrj]

hyperparams:
  max_force: 0.02
  max_steps: 500
  ase_optimizer: FIRE
  loss: MAE
  loss_weights:
    energy: 20
    forces: 20
    stress: 5
    dens: 10
  dens_probability: 0.5
  noise_std: 0.1
  optimizer: AdamW
  learning_rate_schedule: Cosine
  warmup_epochs: 0.1
  warmup_factor: 0.2
  max_learning_rate: 0.0002
  min_learning_rate_factor: 0.01
  grad_clip_threshold: 100
  ema_decay: 0.999
  weight_decay: 0.001
  dropout_rate: 0.1
  stochastic_depth: 0.1
  batch_size: 512
  epochs: 150

notes:
  Description: |
    EquiformerV2 is an equivariant transformer that uses graph attention, attention re-normalization, and separable S^2 activations and layer normalization.
    Denoising Non-Equilibrium Structures (DeNS) uses a denoising generalized to structures with non-zero forces by encoding forces to obtain a well-posed denoising problem.
  Training: |
    Training was done from scratch using MPTrj only and a 50% probability for denoising training structures.

metrics:
  phonons:
    kappa_103:
      k_SRME: 1.8552
      pred_file: models/eqV2_tracegrad/kappa-103-FIRE.json.gz
      pred_file_url:
  geo_opt:
    pred_file: models/eqV2_tracegrad/eqV2-small-dens-tracegrad-geo-opt.json.gz
    struct_col: eqV2-small-dens-tracegrad_structure
    symprec=1e-5:
      rmsd: 0.0732 # unitless
      n_sym_ops_mae: 10.1241 # unitless
      symmetry_decrease: 0.8675 # fraction
      symmetry_match: 0.1319 # fraction
      symmetry_increase: 0.0005 # fraction
      n_structures: 256963 # count
      analysis_file: models/eqV2_tracegrad/eqV2-small-dens-tracegrad-geo-opt-symprec=1e-5-0.3.1.csv.gz
      analysis_file_url:
    symprec=1e-2:
      rmsd: 0.0732 # unitless
      n_sym_ops_mae: 4.0836 # unitless
      symmetry_decrease: 0.3895 # fraction
      symmetry_match: 0.5333 # fraction
      symmetry_increase: 0.0604 # fraction
      n_structures: 256963 # count
      analysis_file: models/eqV2_tracegrad/eqV2-small-dens-tracegrad-geo-opt-symprec=1e-2-0.3.1.csv.gz
      analysis_file_url:
  discovery:
    pred_file: models/eqV2_tracegrad/eqV2-small-dens-tracegrad.csv.gz
    pred_col: e_form_per_atom_eqV2-small-dens-tracegrad
    full_test_set:
      F1: 0.825 # fraction
      DAF: 4.546 # dimensionless
      Precision: 0.78 # fraction
      Recall: 0.876 # fraction
      Accuracy: 0.936 # fraction
      TPR: 0.876 # fraction
      FPR: 0.051 # fraction
      TNR: 0.949 # fraction
      FNR: 0.124 # fraction
      TP: 38614.0 # count
      FP: 10892.0 # count
      TN: 201979.0 # count
      FN: 5478.0 # count
      MAE: 0.032 # eV/atom
      RMSE: 0.081 # eV/atom
      R2: 0.799 # dimensionless
      missing_preds: 2 # count
      missing_percent: 0.00% # fraction
    unique_prototypes:
      F1: 0.843 # fraction
      DAF: 5.242 # dimensionless
      Precision: 0.801 # fraction
      Recall: 0.889 # fraction
      Accuracy: 0.949 # fraction
      TPR: 0.889 # fraction
      FPR: 0.04 # fraction
      TNR: 0.96 # fraction
      FNR: 0.111 # fraction
      TP: 29676.0 # count
      FP: 7358.0 # count
      TN: 174756.0 # count
      FN: 3698.0 # count
      MAE: 0.033 # eV/atom
      RMSE: 0.082 # eV/atom
      R2: 0.802 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
    most_stable_10k:
      F1: 0.988 # fraction
      DAF: 6.382 # dimensionless
      Precision: 0.976 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.976 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9757.0 # count
      FP: 243.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.024 # eV/atom
      RMSE: 0.064 # eV/atom
      R2: 0.908 # dimensionless
      missing_preds: 0 # count
      missing_percent: 0.00% # fraction
