model_name: Nequip-OAM-XL # required (this must match the model's label which is the 3rd arg in the matbench_discovery.preds.Model enum)
model_key: nequip-OAM-XL-0.1 # this should match the name of the YAML file and determines the URL /models/<model_key> on which details of the model are displayed on the website
model_version: '0.1'
date_added: '2025-11-30'
date_published: '2025-11-30'
authors:
  - name: Seán R. Kavanagh
    affiliation: Department of Chemistry, University of Cambridge
    email: sk2045@cam.ac.uk
    orcid: https://orcid.org/0000-0003-4577-9647
    url: https://sam-lab.net
    corresponding: true
  - name: Chuin Wei Tan
    affiliation: MIR Group, Harvard University
  - name: Albert Musaelian
    affiliation: MIR Group, Harvard University & Mirian Technologies
  - name: William C. Witt
    affiliation: MIR Group, Harvard University
  - name: Gabriel de Miranda Nascimento
    affiliation: MIR Group, Harvard University & MIT
  - name: Ulrik Unneberg
    affiliation: MIR Group, Harvard University & MIT
  - name: Marc L. Descoteaux
    affiliation: MIR Group, Harvard University
  - name: Boris Kozinsky
    affiliation: MIR Group, Harvard University
trained_by:
  - name: Seán R. Kavanagh
    affiliation: Department of Chemistry, University of Cambridge
    email: sk2045@cam.ac.uk
    orcid: https://orcid.org/0000-0003-4577-9647
    url: https://sam-lab.net
    corresponding: true

repo: https://github.com/mir-group/nequip
url: https://nequip.readthedocs.io/en/latest/
doi: https://doi.org/10.5281/zenodo.16980200
paper: https://arxiv.org/abs/2504.16068 # To be updated...
checkpoint_url: https://www.nequip.net/models/mir-group/NequIP-OAM-XL:0.1
pr_url: https://github.com/janosh/matbench-discovery/pull/298

openness: OSOD # see `Open` enum in matbench_discovery/enums.py
train_task: S2EFS # see `Task` enum in matbench_discovery/enums.py
test_task: IS2RE-SR # see `Task` enum in matbench_discovery/enums.py
targets: EFS_G # see `Targets` enum in matbench_discovery/enums.py
model_type: UIP # see `ModelType` enum in matbench_discovery/enums.py
model_params: 32_100_000
trained_for_benchmark: true
n_estimators: 1

license:
  code: MIT
  code_url: https://github.com/mir-group/nequip/blob/main/LICENSE
  checkpoint: CC-BY-4.0
  checkpoint_url: https://creativecommons.org/licenses/by/4.0/legalcode

hyperparams:
  max_force: 0.005
  max_steps: 500
  ase_optimizer: GOQN # faster than FIRE with same results; see SI of https://doi.org/10.1088/2515-7655/ade916
  cell_filter: FrechetCellFilter
  optimizer: AdamW
  weight_decay: 1e-8
  graph_construction_radius: 6.0
  sph_harmonics_l_max: 4
  n_layers: 6
  n_features: 320 (l=0 scalars), 96 (l=1 vectors), 64 (l=2 tensors), 32 (l=3,4 tensors)
  parity: false
  zbl_potential: true
  type_embed_num_features: 32
  polynomial_cutoff: 5
  n_radial_bessel_basis: 8
  loss: Huber - delta=0.01 for energy, delta=0.1 for stress, stratified delta (0.01, 0.007, 0.004, 0.001) for force
  loss_weights:
    energy: 1.0
    force: 5.0
    stress: 0.1
  batch_size: 640 # 4 (gpus) * 160 (batch per gpu) = 640 (total batch size)
  initial_learning_rate: 0.005
  gradient_clip_val: 0.25
  learning_rate_schedule: ReduceLROnPlateau - factor=0.1, patience=100, min_lr=1e-6
  epochs: 30 # actual epochs run; max_epochs=100 in Trainer config
  max_neighbors: .inf

training_cost:
  # ~9.8h per epoch, 30 epochs plus fine-tune
  Nvidia H100 GPUs: { amount: 8, hours: 300, cost: 2400 }

requirements:
  torch: '2'
  nequip: '>=0.7.0' # >=0.14.0 recommended

training_set: [OMat24, sAlex, MPtrj]

notes:
  Description: Extra-large NequIP foundation potential; see <https://www.nequip.net/models/mir-group/NequIP-OAM-XL:0.1> for details and <https://arxiv.org/abs/2504.16068> for model/training infrastructure.
  Steps: |
    Training performed by: (1) pre-training on OMat24; (2) fine-tuning on MPtrj+sAlex, with a reduced learning rate (1e-4), energy-loss-upweighting (1:1:0.01 instead of 1:5:0.01) and `StochasticWeightAveraging` (SWA).

metrics:
  phonons:
    kappa_103:
      pred_file: models/nequip/nequip-OAM-XL-0.1/2025-11-30-kappa-103-FIRE-dist=0.03-fmax=0.0001-symprec=1e-05.json.gz
      pred_file_url: https://figshare.com/files/60007844
      κ_SRME: 0.125
      κ_SRE: 0
  geo_opt:
    pred_file: models/nequip/nequip-OAM-XL-0.1/2025-11-30-wbm-IS2RE-GOQN.jsonl.gz
    pred_file_url: https://figshare.com/files/60007799
    struct_col: nequip_structure # same for NequIP/Allegro
    symprec=1e-5:
      rmsd: 0.063 # unitless
      n_sym_ops_mae: 2.0821 # unitless
      symmetry_decrease: 0.0975 # fraction
      symmetry_match: 0.6834 # fraction
      symmetry_increase: 0.2117 # fraction
      n_structures: 256963 # count
      analysis_file: models/nequip/nequip-OAM-XL-0.1/2025-11-30-wbm-IS2RE-GOQN-symprec=1e-5-moyo=0.7.3.csv.gz
      analysis_file_url: https://figshare.com/files/60007817
    symprec=1e-2:
      rmsd: 0.063 # unitless
      n_sym_ops_mae: 1.6986 # unitless
      symmetry_decrease: 0.0253 # fraction
      symmetry_match: 0.8223 # fraction
      symmetry_increase: 0.1437 # fraction
      n_structures: 256963 # count
      analysis_file: models/nequip/nequip-OAM-XL-0.1/2025-11-30-wbm-IS2RE-GOQN-symprec=1e-2-moyo=0.7.3.csv.gz
      analysis_file_url: https://figshare.com/files/60007835
  discovery:
    pred_file: models/nequip/nequip-OAM-XL-0.1/2025-11-30-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/files/60007793
    pred_col: e_form_per_atom_nequip # same for NequIP/Allegro
    full_test_set:
      F1: 0.885 # fraction
      DAF: 5.098 # dimensionless
      Precision: 0.875 # fraction
      Recall: 0.895 # fraction
      Accuracy: 0.96 # fraction
      TPR: 0.895 # fraction
      FPR: 0.027 # fraction
      TNR: 0.973 # fraction
      FNR: 0.105 # fraction
      TP: 39450.0 # count
      FP: 5647.0 # count
      TN: 207224.0 # count
      FN: 4642.0 # count
      MAE: 0.02 # eV/atom
      RMSE: 0.066 # eV/atom
      R2: 0.866 # dimensionless
      missing_preds: 2 # count
    unique_prototypes:
      F1: 0.906 # fraction
      DAF: 5.869 # dimensionless
      Precision: 0.897 # fraction
      Recall: 0.915 # fraction
      Accuracy: 0.971 # fraction
      TPR: 0.915 # fraction
      FPR: 0.019 # fraction
      TNR: 0.981 # fraction
      FNR: 0.085 # fraction
      TP: 30545.0 # count
      FP: 3500.0 # count
      TN: 178614.0 # count
      FN: 2829.0 # count
      MAE: 0.02 # eV/atom
      RMSE: 0.066 # eV/atom
      R2: 0.872 # dimensionless
      missing_preds: 0 # count
    most_stable_10k:
      F1: 0.985 # fraction
      DAF: 6.342 # dimensionless
      Precision: 0.97 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.97 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9695.0 # count
      FP: 305.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.019 # eV/atom
      RMSE: 0.075 # eV/atom
      R2: 0.878 # dimensionless
      missing_preds: 0 # count
