model_name: M3GNet
model_key: m3gnet
model_version: v2022.9.20
dates:
  benchmark_added: '2022-09-20'
  paper_published: '2022-02-05'
lifecycle: active
authors:
- name: Chi Chen
  affiliation: UC San Diego
  orcid: https://orcid.org/0000-0001-8008-7043
  github: https://github.com/chc273
- name: Shyue Ping Ong
  affiliation: UC San Diego
  orcid: https://orcid.org/0000-0001-5726-2587
  email: ongsp@ucsd.edu
  github: https://github.com/shyuep

repo: https://github.com/materialsvirtuallab/m3gnet
doi: https://doi.org/10.1038/s43588-022-00349-3
paper: https://arxiv.org/abs/2202.02450
docs: https://materialsvirtuallab.github.io/m3gnet
pypi: https://pypi.org/project/matgl
pr_url: https://github.com/janosh/matbench-discovery/pull/85
checkpoint_url: https://github.com/materialsvirtuallab/m3gnet/tree/3a8b14dfd5/pretrained/MP-2021.2.8-EFS
license:
  code: BSD-3-Clause
  code_url: https://github.com/materialsvirtuallab/m3gnet/blob/3a8b14dfd59/LICENSE
  checkpoint: MIT
  checkpoint_url: https://github.com/materialsvirtuallab/m3gnet/blob/3a8b14dfd59/LICENSE

environment:
  dependencies:
  - matgl==3.0.5
  - dgl==2.4.0
  - torch==2.4.0
  - m3gnet==0.1.0
  - pymatgen==2022.10.22
  - numpy==1.26.4
  - pandas==1.5.1
  python_version: '3.11'
  find_links: ['https://data.dgl.ai/wheels/torch-2.4/cu121/repo.html']
openness: OSOD
architecture_types: [gnn]
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
training_sets: [MPF]
model_params: 227549
hyperparams:
  evaluation:
    ase_optimizer: FIRE
    cell_filter: ExpCellFilter
    max_steps: 500
    max_force: 0.05
    kappa:
      protocol: phonondb-v1
  architecture:
    graph_construction_radius: 5.0
  training:
    batch_size: 32
    learning_rate: 0.001
    optimizer: Adam
  upstream_config:
    loss_weights:
      energy: 1
      force: 1
      stress: 0.1
    three_body_cutoff: 4.0
notes:
  description: M3GNet is a GNN-based universal (as in full periodic table) interatomic potential for materials trained on up to 3-body interactions in the initial, middle and final frame of MP DFT relaxations.
  long: It thereby learns to emulate structure relaxation, MD simulations and property prediction of materials across diverse chemical spaces.
  training: Using pre-trained model released with paper. Was only trained on initial, middle and final frames of a subset of 62,783 MP relaxation trajectories in the 2018 database release (see [related issue](https://github.com/materialsvirtuallab/m3gnet/issues/20#issuecomment-1207087219)).
  testing: We also tried combining M3GNet with MEGNet where M3GNet is used to relax initial structures which are then passed to MEGNet to predict the formation energy.

metrics:
  discovery:
    pred_file:
      name: models/m3gnet/m3gnet/2023-12-28-discovery.csv.gz
      url: https://figshare.com/files/52057535
      size: 2377101
      md5: b309e4a28d8f91814e7fb7ca1160bc8c
    pred_col: e_form_per_atom_m3gnet
    full_test_set:
      F1: 0.576  # fraction
      DAF: 2.647 # dimensionless
      Precision: 0.454 # fraction
      Recall: 0.788 # fraction
      Accuracy: 0.801 # fraction
      TPR: 0.788 # fraction
      FPR: 0.196 # fraction
      TNR: 0.804 # fraction
      FNR: 0.212 # fraction
      TP: 34731 # count
      FP: 41738 # count
      TN: 171133 # count
      FN: 9361 # count
      MAE: 0.072 # eV/atom
      RMSE: 0.115 # eV/atom
      R2: 0.588 # dimensionless
      missing_preds: 355 # count
    most_stable_10k:
      F1: 0.868  # fraction
      DAF: 5.02 # dimensionless
      Precision: 0.767 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.767 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 7674 # count
      FP: 2326 # count
      TN: 0 # count
      FN: 0 # count
      MAE: 0.101 # eV/atom
      RMSE: 0.158 # eV/atom
      R2: 0.551 # dimensionless
      missing_preds: 0 # count
    unique_prototypes:
      F1: 0.569  # fraction
      DAF: 2.882 # dimensionless
      Precision: 0.441 # fraction
      Recall: 0.803 # fraction
      Accuracy: 0.812 # fraction
      TPR: 0.803 # fraction
      FPR: 0.187 # fraction
      TNR: 0.813 # fraction
      FNR: 0.197 # fraction
      TP: 26797 # count
      FP: 34034 # count
      TN: 148080 # count
      FN: 6577 # count
      MAE: 0.075 # eV/atom
      RMSE: 0.118 # eV/atom
      R2: 0.585 # dimensionless
      missing_preds: 299 # count
  geo_opt:
    pred_file:
      name: models/m3gnet/m3gnet/2023-06-01-geo-opt.jsonl.gz
      url: https://figshare.com/files/57751024
      size: 118487634
      md5: f82191618b2958811c4069e9a2031662
    symprec=1e-5:
      rmsd: 0.1117
      n_sym_ops_mae: 1.8691
      symmetry_decrease: 0.0671
      symmetry_match: 0.7408
      symmetry_increase: 0.1869
      n_structures: 256963
      analysis_file:
        name: models/m3gnet/m3gnet/2023-06-01-geo-opt-symprec=1e-5-moyo=0.4.2.csv.gz
        url: https://figshare.com/files/53504594
        size: 7062559
        md5: 18448ea8867f4e2fb35158d0a7020505
    symprec=1e-2:
      rmsd: 0.1117
      n_sym_ops_mae: 1.9848
      symmetry_decrease: 0.0681
      symmetry_match: 0.8031
      symmetry_increase: 0.1217
      n_structures: 256963
      analysis_file:
        name: models/m3gnet/m3gnet/2023-06-01-geo-opt-symprec=1e-2-moyo=0.4.2.csv.gz
        url: https://figshare.com/files/53504600
        size: 7115973
        md5: dc5735aaad87d65a3b74f3ed18988a41
  phonons:
    kappa_103:
      κ_SRME: 1.4094
      pred_file:
        name: models/m3gnet/m3gnet/2024-11-09-phonons-kappa-103.json.gz
        url: https://figshare.com/files/52134866
        size: 18034939
        md5: 5bf90c8e0e755132b88a2875ff111f12
      κ_SRE: 1.3404
