model_name: M3GNet
model_version: 2022.9.20
matbench_discovery_version: 1.0.0
date_added: "2022-09-20"
date_published: "2022-02-05"
authors:
  - name: Chi Chen
    affiliation: UC San Diego
    role: Model
    orcid: https://orcid.org/0000-0001-8008-7043
  - name: Shyue Ping Ong
    affiliation: UC San Diego
    orcid: https://orcid.org/0000-0001-5726-2587
    email: ongsp@ucsd.edu
repo: https://github.com/materialsvirtuallab/m3gnet
url: https://materialsvirtuallab.github.io/m3gnet
doi: https://doi.org/10.1038/s43588-022-00349-3
paper: https://arxiv.org/abs/2202.02450
pypi: https://pypi.org/project/matgl

requirements:
  m3gnet: 0.1.0
  pymatgen: 2022.10.22
  numpy: 1.24.0
  pandas: 1.5.1

openness: OSOD
trained_for_benchmark: false
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS
model_type: UIP
model_params: 227_549
n_estimators: 1

hyperparams:
  batch_size: 32
  learning_rate: 1e-3
  optimizer: Adam
  loss_weights: { energy: 1, force: 1, stress: 0.1 }

training_set:
  title: MPF.2021.2.8
  url: https://figshare.com/articles/dataset/19470599
  n_structures: 188_349
  n_materials: 62_783

notes:
  Description: M3GNet is a GNN-based universal (as in full periodic table) interatomic potential for materials trained on up to 3-body interactions in the initial, middle and final frame of MP DFT relaxations.
  Long: It thereby learns to emulate structure relaxation, MD simulations and property prediction of materials across diverse chemical spaces.
  Training: Using pre-trained model released with paper. Was only trained on initial, middle and final frames of a subset of 62,783 MP relaxation trajectories in the 2018 database release (see [related issue](https://github.com/materialsvirtuallab/m3gnet/issues/20#issuecomment-1207087219)).
  Testing: We also tried combining M3GNet with MEGNet where M3GNet is used to relax initial structures which are then passed to MEGNet to predict the formation energy.
