model_name: Nequix MP PFT
model_key: nequix-mp-1-pft
model_version: '0.1.0'
date_added: '2026-01-08'
date_published: '2026-01-08'
authors:
  - name: Teddy Koker
    affiliation: Massachusetts Institute of Technology
    email: tekoker@mit.edu
    url: https://teddykoker.com
    orcid: https://orcid.org/0000-0001-8861-9788
  - name: Abhijeet Gangan
    affiliation: University of California, Los Angeles
    email: abhijeetgangan@g.ucla.edu
    orcid: https://orcid.org/0000-0002-8937-7984
  - name: Mit Kotak
    affiliation: Massachusetts Institute of Technology
    email: mkotak@mit.edu
    orcid: https://orcid.org/0000-0002-6999-1055
  - name: Jaime Marian
    affiliation: University of California, Los Angeles
    email: jmarian@g.ucla.edu
    orcid: https://orcid.org/0000-0001-9000-3405
  - name: Tess Smidt
    affiliation: Massachusetts Institute of Technology
    email: tsmidt@mit.edu
    url: https://blondegeek.github.io/
    orcid: https://orcid.org/0000-0001-5581-5344

trained_by:
  - name: Teddy Koker
    affiliation: Massachusetts Institute of Technology
    email: tekoker@mit.edu
    url: https://teddykoker.com
    orcid: https://orcid.org/0000-0001-8861-9788

repo: https://github.com/atomicarchitects/nequix
url: https://github.com/atomicarchitects/nequix
doi: https://doi.org/10.48550/arXiv.2601.07742
paper: https://arxiv.org/abs/2601.07742
pr_url: https://github.com/janosh/matbench-discovery/pull/304
checkpoint_url: https://figshare.com/files/60965527

openness: OSOD
train_task: S2EFS
test_task: IS2RE-SR
targets: EFSH_G
model_type: UIP
model_params: 707_658
trained_for_benchmark: true
n_estimators: 1

license:
  code: MIT
  code_url: https://github.com/atomicarchitects/nequix/blob/main/LICENSE
  checkpoint: CC-BY-4.0
  checkpoint_url: https://creativecommons.org/licenses/by/4.0/

hyperparams:
  max_force: 0.02
  max_steps: 500
  ase_optimizer: FIRE
  cell_filter: FrechetCellFilter
  hidden_irreps: 128x0e+64x1o+32x2e+32x3o
  graph_construction_radius: 6.0
  max_neighbors: .inf
  lmax: 3
  radial_basis_size: 8
  radial_mlp_size: 64
  radial_mlp_layers: 2
  radial_polynomial_p: 6.0
  layer_norm: true

  optimizer: adamw
  learning_rate: 0.0001
  weight_decay: 0.001
  grad_clip_norm: 100
  batch_size: 16
  n_epochs: 100
  loss:
    energy: mae
    force: l2
    stress: mae
    hessian: mae
  loss_weights:
    energy: 0.0
    force: 20.0
    stress: 5.0
    hessian: 100.0
  cotrain_loss_weights:
    energy: 500.0
    force: 200.0
    stress: 50.0
  ema_decay: 0.999

training_cost:
  Nvidia A100 GPUs: { amount: 1, hours: 140 }

training_set: [MPtrj, MDR PBE Phonons in MPtrj]

notes:
  Description: Nequix MP PFT is a fine-tuned version of Nequix MP 1, which was fine-tuned using phonon fine-tuning (PFT) on a subset of the MDR Phonon PBE dataset that is contained within MPtrj.
  Reproduction: |
    git clone https://github.com/atomicarchitects/nequix.git && cd nequix
    uv sync --extra pft
    bash data/download_pbe_mdr_preprocessed.sh
    uv run nequix/pft/train.py configs/nequix-mp-1-pft.yml

requirements:
  jax: 0.6.2
  e3nn-jax: 0.20.7
  jraph: 0.0.6.dev0
  equinox: 0.11.11
  optax: 0.2.5
  ase: 3.24.0
  tqdm: 4.67.1
  wandb: 0.19.11
  pyyaml: 6.0.2
  matscipy: 1.1.1
  h5py: 3.14.0
  wandb-osh: 1.2.2
  cloudpickle: 3.1.1

metrics:
  phonons:
    kappa_103:
      pred_file: models/nequix/nequix-mp-1-pft/2026-01-12-kappa-103-FIRE-dist=0.03-fmax=1e-4-symprec=1e-5.json.gz
      pred_file_url: https://figshare.com/files/61019518
      κ_SRME: 0.3066
      κ_SRE: 0.1689
  geo_opt:
    pred_file: models/nequix/nequix-mp-1-pft/2026-01-12-wbm-IS2RE-FIRE.jsonl.gz
    pred_file_url: https://figshare.com/files/61019686
    struct_col: nequix-mp-pft-1yqa7d5t-200epochs_structure
    symprec=1e-2:
      rmsd: 0.0866 # unitless
      n_sym_ops_mae: 1.7984 # unitless
      symmetry_decrease: 0.054 # fraction
      symmetry_match: 0.8109 # fraction
      symmetry_increase: 0.1276 # fraction
      n_structures: 256963 # count
      analysis_file: models/nequix/nequix-mp-1-pft/2026-01-12-wbm-IS2RE-FIRE-symprec=1e-2-moyo=0.7.4.csv.gz
      analysis_file_url: https://figshare.com/files/61021306
    symprec=1e-5:
      rmsd: 0.0866 # unitless
      n_sym_ops_mae: 2.0578 # unitless
      symmetry_decrease: 0.0602 # fraction
      symmetry_match: 0.6976 # fraction
      symmetry_increase: 0.2362 # fraction
      n_structures: 256963 # count
      analysis_file: models/nequix/nequix-mp-1-pft/2026-01-12-wbm-IS2RE-FIRE-symprec=1e-5-moyo=0.7.4.csv.gz
      analysis_file_url: https://figshare.com/files/61021309
  discovery:
    pred_file: models/nequix/nequix-mp-1-pft/2026-01-12-wbm-IS2RE.csv.gz
    pred_file_url: https://figshare.com/files/61019521
    pred_col: e_form_per_atom_nequix
    full_test_set:
      F1: 0.74 # fraction
      DAF: 3.963 # dimensionless
      Precision: 0.68 # fraction
      Recall: 0.811 # fraction
      Accuracy: 0.902 # fraction
      TPR: 0.811 # fraction
      FPR: 0.079 # fraction
      TNR: 0.921 # fraction
      FNR: 0.189 # fraction
      TP: 35757.0 # count
      FP: 16821.0 # count
      TN: 196050.0 # count
      FN: 8335.0 # count
      MAE: 0.042 # eV/atom
      RMSE: 0.084 # eV/atom
      R2: 0.783 # dimensionless
      missing_preds: 2 # count
    unique_prototypes:
      F1: 0.748 # fraction
      DAF: 4.479 # dimensionless
      Precision: 0.685 # fraction
      Recall: 0.825 # fraction
      Accuracy: 0.914 # fraction
      TPR: 0.825 # fraction
      FPR: 0.07 # fraction
      TNR: 0.93 # fraction
      FNR: 0.175 # fraction
      TP: 27533.0 # count
      FP: 12676.0 # count
      TN: 169438.0 # count
      FN: 5841.0 # count
      MAE: 0.044 # eV/atom
      RMSE: 0.085 # eV/atom
      R2: 0.784 # dimensionless
      missing_preds: 0 # count
    most_stable_10k:
      F1: 0.953 # fraction
      DAF: 5.95 # dimensionless
      Precision: 0.91 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.91 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9096.0 # count
      FP: 904.0 # count
      TN: 0.0 # count
      FN: 0.0 # count
      MAE: 0.051 # eV/atom
      RMSE: 0.114 # eV/atom
      R2: 0.744 # dimensionless
      missing_preds: 0 # count
