model_name: Nequix MP
model_key: nequix-mp-1
model_version: '0.1.0'
dates:
  benchmark_added: '2025-08-17'
  paper_published: '2025-08-17'
lifecycle: active
authors:
- name: Teddy Koker
  affiliation: Massachusetts Institute of Technology
  email: tekoker@mit.edu
  url: https://teddykoker.com
  orcid: https://orcid.org/0000-0001-8861-9788
- name: Tess Smidt
  affiliation: Massachusetts Institute of Technology
  email: tsmidt@mit.edu
  url: https://blondegeek.github.io/
  orcid: https://orcid.org/0000-0001-5581-5344

trained_by:
- name: Teddy Koker
  affiliation: Massachusetts Institute of Technology
  email: tekoker@mit.edu
  url: https://teddykoker.com
  orcid: https://orcid.org/0000-0001-8861-9788

repo: https://github.com/atomicarchitects/nequix
doi: https://doi.org/10.48550/arXiv.2508.16067
paper: https://arxiv.org/abs/2508.16067
docs: https://github.com/atomicarchitects/nequix
pr_url: https://github.com/janosh/matbench-discovery/pull/276
checkpoint_url: https://figshare.com/files/57245573
license:
  code: MIT
  code_url: https://github.com/atomicarchitects/nequix/blob/main/LICENSE
  checkpoint: CC-BY-4.0
  checkpoint_url: https://creativecommons.org/licenses/by/4.0/

environment:
  dependencies:
  - nequix
  - 'jax[cuda12]'
  - e3nn-jax==0.20.7
  - jraph==0.0.6.dev0
  - equinox==0.11.11
  - optax==0.2.5
  - ase==3.24.0
  - tqdm==4.67.1
  - wandb==0.19.11
  - pyyaml==6.0.2
  - matscipy==1.1.1
  - h5py==3.14.0
  - wandb-osh==1.2.2
  - cloudpickle==3.1.1
  python_version: '3.12'
openness: OSOD
architecture_types: [gnn]
train_task: S2EFS
test_task: IS2RE-SR
targets: EFS_G
training_sets: [MPtrj]
model_params: 707658
training_cost:
  entries:
  - hardware: NVIDIA A100
    count: 4
    hours_per_device: 125.0
hyperparams:
  evaluation:
    max_force: 0.02
    max_steps: 500
    ase_optimizer: FIRE
    cell_filter: FrechetCellFilter
    kappa:
      protocol: phonondb-v1
      displacement_distance: 0.03
      max_steps: 500
      force_max: 0.02
      save_forces: true
  architecture:
    graph_construction_radius: 6.0
  training:
    batch_size: 256
    epochs: 100
    optimizer: Muon
  upstream_config:
    hidden_irreps: 128x0e+64x1o+32x2e+32x3o
    lmax: 3
    radial_basis_size: 8
    radial_mlp_size: 64
    radial_mlp_layers: 2
    radial_polynomial_p: 6.0
    layer_norm: true
    weight_decay: 0.001
    warmup_epochs: 0.1
    warmup_factor: 0.2
    grad_clip_norm: 100
    loss:
      energy: mae
      force: l2
      stress: mae
    loss_weights:
      energy: 20.0
      force: 20.0
      stress: 5.0
    ema_decay: 0.999
notes:
  description: Nequix is a simplified version of NequIP with added RMSnorm, implemented in JAX, and trained with Muon optimizer.

metrics:
  diatomics:
    pred_file:
      name: models/nequix/nequix-mp-1/2026-06-28-diatomics.json.gz
      url: https://figshare.com/files/66104669
      size: 242473
      md5: 297aecca67628880c944c0a8d7b0152a
    hardware: NVIDIA H200
    run_time_sec: 56.83
    pbe_wall_dist_mae: 0.6649
    pbe_energy_mae: 1.707
    pbe_bond_length_error: 0.2886
    pbe_well_depth_error: 0.5733
    pbe_vib_freq_error: 90.36
    tortuosity: 1.306
    energy_diff_flips: 2.172
    energy_jump: 0.5506
    force_flips: 2.172
    force_total_variation: 79.92
    force_jump: 16.73
    pbe_force_mae: 2.91
  discovery:
    pred_file:
      name: models/nequix/nequix-mp-1/2025-08-17-discovery.csv.gz
      url: https://figshare.com/files/66646199
      size: 1376646
      md5: 75027984e17c77bfacc160e9e6078c90
    full_test_set:
      F1: 0.744  # fraction
      DAF: 3.95 # dimensionless
      Precision: 0.678 # fraction
      Recall: 0.825 # fraction
      Accuracy: 0.903 # fraction
      TPR: 0.825 # fraction
      FPR: 0.081 # fraction
      TNR: 0.919 # fraction
      FNR: 0.175 # fraction
      TP: 36363 # count
      FP: 17282 # count
      TN: 195589 # count
      FN: 7729 # count
      MAE: 0.042 # eV/atom
      RMSE: 0.084 # eV/atom
      R2: 0.78 # dimensionless
      missing_preds: 2 # count
    unique_prototypes:
      F1: 0.751  # fraction
      DAF: 4.455 # dimensionless
      Precision: 0.681 # fraction
      Recall: 0.836 # fraction
      Accuracy: 0.914 # fraction
      TPR: 0.836 # fraction
      FPR: 0.072 # fraction
      TNR: 0.928 # fraction
      FNR: 0.164 # fraction
      TP: 27898 # count
      FP: 13064 # count
      TN: 169050 # count
      FN: 5476 # count
      MAE: 0.044 # eV/atom
      RMSE: 0.086 # eV/atom
      R2: 0.782 # dimensionless
      missing_preds: 0 # count
    most_stable_10k:
      F1: 0.953  # fraction
      DAF: 5.949 # dimensionless
      Precision: 0.91 # fraction
      Recall: 1.0 # fraction
      Accuracy: 0.91 # fraction
      TPR: 1.0 # fraction
      FPR: 1.0 # fraction
      TNR: 0.0 # fraction
      FNR: 0.0 # fraction
      TP: 9095 # count
      FP: 905 # count
      TN: 0 # count
      FN: 0 # count
      MAE: 0.051 # eV/atom
      RMSE: 0.117 # eV/atom
      R2: 0.734 # dimensionless
      missing_preds: 0 # count
  geo_opt:
    pred_file:
      name: models/nequix/nequix-mp-1/2025-08-17-geo-opt.jsonl.gz
      url: https://figshare.com/files/57262715
      size: 143983625
      md5: 945c16a045d4de33ea2b1980c13a565e
    symprec=1e-5:
      rmsd: 0.0853
      n_sym_ops_mae: 2.0462
      symmetry_decrease: 0.0607
      symmetry_match: 0.6999
      symmetry_increase: 0.2335
      n_structures: 256963
      analysis_file:
        name: models/nequix/nequix-mp-1/2025-08-17-geo-opt-symprec=1e-5-moyo=0.4.4.csv.gz
        url: https://figshare.com/files/57262718
        size: 7721146
        md5: 78de4441c4e6b15640024232507987a0
    symprec=1e-2:
      rmsd: 0.0853
      n_sym_ops_mae: 1.7969
      symmetry_decrease: 0.0554
      symmetry_match: 0.8111
      symmetry_increase: 0.1261
      n_structures: 256963
      analysis_file:
        name: models/nequix/nequix-mp-1/2025-08-17-geo-opt-symprec=1e-2-moyo=0.4.4.csv.gz
        url: https://figshare.com/files/57262721
        size: 7750203
        md5: 891f6a640653e9f2f2bfb666e28ea290
  md:
    pred_file:
      name: models/nequix/nequix-mp-1/2026-06-28-md-metrics.csv.gz
      url: https://figshare.com/files/66048917
      size: 1537
      md5: 6e73570ab21e751d1615eb6c7fff0a9e
    hardware: NVIDIA H200
    run_time_sec: 41313.81
    energy_rmse: 1.3652
    force_rmse: 136.1155
    rdf_error: 6.085
    adf_error: 2.7458
    vdos_error: 27.6748
    pressure_mae: 0.9578
    pressure_wasserstein: 0.9596
    pressure_error: 73.8322
    n_systems: 17
  phonons:
    kappa_103:
      pred_file:
        name: models/nequix/nequix-mp-1/2025-08-17-phonons-kappa-103.json.gz
        url: https://figshare.com/files/57262724
        size: 8149313
        md5: 8328bd20f4697ce0b467d56bd683c8f0
      κ_SRME: 0.4461
      κ_SRE: 0.2901
      κ_SRD: -0.2477
      κ_failure_rate: 0.0
      imaginary_mode_rate: 0.0
      spectrum_w1: 0.516
