name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  release:
    runs-on: ubuntu-latest
    needs: tests
    if: needs.tests.result == 'success'
    permissions:
      id-token: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build and upload dist
        run: |
          pip install build twine
          python -m build
          twine check dist/* --strict

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
