name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/test.yml

  release:
    needs: tests
    if: needs.tests.result == 'success'
    permissions:
      id-token: write
    uses: janosh/workflows/.github/workflows/pypi-publish.yml@main
