name: Run slow tests after PR merge

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  slow-tests:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -e .[test]

      - name: Run slow tests
        run: pytest -m slow
